begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
create temp table label_tap_results(result text);
do $label_checks$
declare
 actor uuid:=(select user_id from public.employees where role='admin' and active is distinct from false limit 1);
 seller uuid:=(select id from public.employees where user_id=actor limit 1);
 other_actor uuid:=(select id from auth.users where id<>actor limit 1);
 event text:='EARLY-LABEL-'||replace(gen_random_uuid()::text,'-','');
 show public.live_sale_sessions;l public.live_sale_lots;again public.live_sale_lots;
 a uuid;b uuid;obs jsonb;state_value text;
begin
 insert into label_tap_results select no_plan();
 perform set_config('request.jwt.claim.sub',actor::text,true);
 insert into label_tap_results select ok(not has_function_privilege('anon','public.prepare_ebay_live_bag_label(uuid)','EXECUTE'),'anonymous cannot prepare labels');
 show:=public.start_ebay_live_session('__early_label_test',null,event,seller);
 obs:=jsonb_build_object('key','won','kind','won','listing_id','777777777772','title','#001 - Test ring','buyer','labelwinner','amount',600,'currency','USD','time_label','12:00 PM','source','activity','observed_at',clock_timestamp());
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs),jsonb_build_object('observed_at',clock_timestamp(),'ready',true));
 select id into a from public.ebay_live_attempts where event_id=event and win_key='won';
 insert into label_tap_results select throws_ok(format('select public.prepare_ebay_live_bag_label(%L)',a),'22023','Payment is not confirmed for this bag','waiting payment cannot prepare a label');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"paid","kind":"paid"}'),jsonb_build_object('observed_at',clock_timestamp(),'ready',true));
 l:=public.prepare_ebay_live_bag_label(a);
 insert into label_tap_results select ok(l.lot_code like 'LIVE-%','paid auction receives a unique QR bag ID before scanning');
 insert into label_tap_results select is(l.status,'open','label leaves bag open');
 insert into label_tap_results select is(l.owner_employee_id,seller,'label preserves credited seller');
 insert into label_tap_results select ok(l.closed_at is null,'label does not close bag');
 insert into label_tap_results select ok((select claimed_by is null and claimed_at is null and closed_at is null from public.ebay_live_attempts where id=a),'label does not claim or complete scanning');
 insert into label_tap_results select is((select lot_id from public.ebay_live_attempts where id=a),l.id,'label linked to the paid auction');
 insert into label_tap_results select is((select count(*)::int from public.live_sale_lot_items where lot_id=l.id),0,'label does not reserve inventory');
 insert into label_tap_results select is((select count(*)::int from public.live_sale_manual_lot_items where lot_id=l.id),0,'label does not create manual contents');
 again:=public.prepare_ebay_live_bag_label(a);
 insert into label_tap_results select is(again.id,l.id,'retry returns the same bag');
 insert into label_tap_results select is(again.lot_code,l.lot_code,'reprint preserves the QR');
 insert into label_tap_results select is((select count(*)::int from public.ebay_live_audit where attempt_id=a and action='bag_label_prepared'),1,'retry does not duplicate creation audit');
 update public.ebay_live_attempts set claimed_by=other_actor,claimed_at=now() where id=a;
 again:=public.prepare_ebay_live_bag_label(a);
 insert into label_tap_results select is((select claimed_by from public.ebay_live_attempts where id=a),other_actor,'printing does not steal another scanner claim');
 update public.ebay_live_attempts set claimed_by=null,claimed_at=null where id=a;
 again:=public.claim_ebay_live_bag(a);
 insert into label_tap_results select is(again.id,l.id,'scanner later recovers the already printed bag');
 insert into label_tap_results select throws_ok(format('select public.close_ebay_live_bag(%L)',a),'22023','Scan the sold item before closing the bag','an empty printed bag cannot be closed');
 foreach state_value in array array['waiting','failed','cancelled','review'] loop
  update public.ebay_live_attempts set payment_state=state_value where id=a;
  insert into label_tap_results select throws_ok(format('select public.prepare_ebay_live_bag_label(%L)',a),'22023','Payment is not confirmed for this bag',state_value||' blocks reprints');
 end loop;
 update public.ebay_live_attempts set payment_state='paid',resolved_at=now() where id=a;
 insert into label_tap_results select throws_ok(format('select public.prepare_ebay_live_bag_label(%L)',a),'22023','Payment is not confirmed for this bag','resolved sale blocks label');
 update public.ebay_live_attempts set resolved_at=null where id=a;
 update public.live_sale_lots set status='released' where id=l.id;
 insert into label_tap_results select throws_ok(format('select public.prepare_ebay_live_bag_label(%L)',a),'22023','Payment is not confirmed for this bag','released bag blocks label');
 update public.live_sale_lots set status='open' where id=l.id;
 insert into public.ebay_live_attempts(event_id,listing_id,listing_title,buyer,amount,payment_state,seller_id) values(event,'777777777773','#001 - Rerun','anotherwinner',500,'paid',seller) returning id into b;
 again:=public.prepare_ebay_live_bag_label(b);
 insert into label_tap_results select isnt(again.lot_code,l.lot_code,'same auction number still has a different bag QR for another win');
 perform public.mark_ebay_live_broadcast_ended(event);
 insert into label_tap_results select throws_ok(format('select public.complete_ebay_live_session(%L,true,true)',show.id),'22023','Finish all paid bags and resolve outstanding payments, notifications and unlinked bags before closing','printing does not bypass final packing checks');
 perform set_config('request.jwt.claim.sub','',true);
 insert into label_tap_results select throws_ok(format('select public.prepare_ebay_live_bag_label(%L)',a),'42501','Inventory access required','unauthenticated label preparation rejected');
 insert into label_tap_results select * from finish();
end $label_checks$;
select * from label_tap_results;
rollback;
