begin;
set local statement_timeout='30s';
create or replace function pg_temp.verify(ok boolean,label text) returns void language plpgsql as $$
begin if ok is distinct from true then raise exception 'Failed: %',label;end if;raise notice 'ok %',label;end $$;
do $$
declare actor uuid:=(select user_id from public.employees where role='admin' and active is distinct from false limit 1);
 seller uuid:=(select id from public.employees where user_id=actor limit 1);
 other uuid:=(select id from public.employees where id<>seller and active is distinct from false limit 1);
 event text:='TEST-'||replace(gen_random_uuid()::text,'-','');
 legacy text:='TEST-'||replace(gen_random_uuid()::text,'-','');
 s public.live_sale_sessions;retry public.live_sale_sessions;bag public.live_sale_lots;auction uuid;second_sale uuid;ord uuid;line uuid;before_count bigint;
 stream jsonb:='{"source":"ebay_event_information","title":"Original eBay show","start_local":"2026-08-23T23:30","timezone_label":"EDT","activity_timezone":"America/New_York"}';
 obs jsonb:='{"key":"win-1","kind":"won","listing_id":"123456789012","title":"#001 - Historical watch","buyer":"history-fixture","amount":100,"currency":"USD","ordinal":"1","time_label":"12:15 AM","source":"activity"}';
begin
 perform set_config('request.jwt.claim.sub',actor::text,true);
 perform pg_temp.verify(not has_function_privilege('anon','public.start_ebay_live_capture_from_stream(text,uuid,uuid[],jsonb)','execute'),'anonymous cannot start dated capture');
 perform pg_temp.verify(not has_function_privilege('authenticated','public.ebay_live_activity_time(timestamptz,text,text)','execute'),'timing helper is internal');
 perform pg_temp.verify(public.ebay_live_activity_time('2026-08-24 03:30Z','America/New_York','12:15 AM')='2026-08-24 04:15Z','sale after midnight uses following date');
 perform pg_temp.verify(public.ebay_live_activity_time('2026-09-30 18:05Z','America/New_York','3:33 PM')='2026-09-30 19:33Z','actual eBay page clock matches original event date');
 perform pg_temp.verify(public.ebay_live_activity_time('2026-09-30 18:05Z','America/New_York','2:01 PM')='2026-09-30 18:01Z','slightly early sale stays on same date');
 perform pg_temp.verify(public.ebay_live_activity_time('2026-11-01 04:30Z','America/New_York','1:30 AM') is null,'repeated daylight-saving clock is not guessed');
 perform pg_temp.verify(public.ebay_live_activity_time('2026-03-08 05:30Z','America/New_York','2:30 AM') is null,'nonexistent daylight-saving clock is not guessed');
 perform pg_temp.verify(public.ebay_live_activity_time('2026-08-24 03:30Z','America/Los_Angeles','9:15 PM')='2026-08-24 04:15Z','viewer timezone can differ from event timezone');
 perform pg_temp.verify(public.ebay_live_activity_time('2026-08-24 03:30Z','America/New_York','13:99 PM') is null,'malformed Activity clock remains unknown');
 select count(*) into before_count from public.live_sale_sessions;
 begin perform public.start_ebay_live_capture_from_stream(event,seller,'{}',stream||'{"timezone_label":"UNKNOWN"}');raise exception 'Invalid timezone accepted';exception when invalid_parameter_value then null;end;
 perform pg_temp.verify((select count(*) from public.live_sale_sessions)=before_count,'bad metadata rolls back whole setup');
 s:=public.start_ebay_live_capture_from_stream(event,seller,array[other],stream);
 perform pg_temp.verify(s.started_at='2026-08-24 03:30Z' and s.title='Original eBay show','show retains original saved eBay date and title');
 retry:=public.start_ebay_live_capture_from_stream(event,other,'{}',stream);
 perform pg_temp.verify(retry.id=s.id and retry.primary_seller_employee_id=seller,'retry keeps original chosen seller');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs),jsonb_build_object('stream',stream,'broadcast_ended',true,'observed_at',now()));
 select id into auction from public.ebay_live_attempts where event_id=event and win_key='win-1';
 perform pg_temp.verify((select sold_at='2026-08-24 04:15Z' and sale_time_source='ebay_activity' and sale_time_precision='minute' and seller_id=seller and created_at>sold_at from public.ebay_live_attempts where id=auction),'recovered sale uses eBay minute and selected seller, with separate capture audit');
 perform pg_temp.verify((public.get_ebay_live_dashboard(s.id)->'attempts'->0->>'sold_at')::timestamptz='2026-08-24 04:15Z','dashboard exposes the original sale date');
 perform public.set_ebay_live_seller(event,other,false);
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"win-2","listing_id":"222222222222","time_label":"12:20 AM"}'),jsonb_build_object('stream',stream,'broadcast_ended',true));
 select id into second_sale from public.ebay_live_attempts where event_id=event and win_key='win-2';
 perform pg_temp.verify((select seller_id=seller from public.ebay_live_attempts where id=second_sale),'late recovered history keeps initial selected seller');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"paid","kind":"paid","source":"listing"}'),jsonb_build_object('stream',stream));
 bag:=public.claim_ebay_live_bag(auction);
 perform public.correct_ebay_live_sale_sellers(event,array[auction],other,'Correct only the selected historical bag.');
 perform pg_temp.verify((select seller_id=other from public.ebay_live_attempts where id=auction) and (select owner_employee_id=other from public.live_sale_lots where id=bag.id),'selected seller correction updates sale and bag');
 perform pg_temp.verify((select seller_id=seller from public.ebay_live_attempts where id=second_sale),'selected seller correction leaves other sales unchanged');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs),jsonb_build_object('stream',stream));
 perform pg_temp.verify((select count(*)=2 from public.ebay_live_attempts where event_id=event) and (select seller_id=other from public.ebay_live_attempts where id=auction),'recapture preserves corrected sellers without duplicates');
 perform public.update_live_sale_lot_owner(bag.id,seller,'fixture@example.invalid');
 perform pg_temp.verify((select seller_id=seller from public.ebay_live_attempts where id=auction),'existing signed bag correction also updates sale seller');
 perform public.set_ebay_live_seller(event,other,true,'Correct every historical bag for this show.');
 perform pg_temp.verify(not exists(select 1 from public.ebay_live_attempts where event_id=event and seller_id<>other) and (select owner_employee_id=other from public.live_sale_lots where id=bag.id),'whole show correction updates all sales and bags');
 begin perform public.correct_ebay_live_sale_sellers(event,array[auction,gen_random_uuid()],seller,'Invalid cross show selection.');raise exception 'Invalid selection accepted';exception when invalid_parameter_value then null;end;
 perform pg_temp.verify((select seller_id=other from public.ebay_live_attempts where id=auction),'invalid selection is atomic');
 begin perform public.apply_ebay_live_stream_metadata(event,stream||'{"activity_timezone":"America/Chicago"}');raise exception 'Mixed clock timezones accepted';exception when invalid_parameter_value then null;end;
 perform pg_temp.verify(true,'mixed capture timezones do not reinterpret existing clocks');
 insert into public.ebay_orders(order_number,buyer_username,sale_date,raw_payload) values('__time_fixture_'||gen_random_uuid(),'history-fixture','2026-08-24 06:15Z','{"orderPaymentStatus":"PAID"}') returning id into ord;
 insert into public.ebay_order_lines(order_id,item_number,transaction_id,item_title,sold_for,quantity) values(ord,'123456789012','time-fixture','Historical watch',100,1) returning id into line;
 perform public.reconcile_ebay_live_orders_internal(event);
 perform pg_temp.verify((select order_line_id=line and sold_at='2026-08-24 04:15Z' from public.ebay_live_attempts where id=auction),'historical order matches a range without replacing original Activity time');
 -- A previously captured win is repaired when the event metadata arrives later.
 retry:=public.start_ebay_live_capture(legacy,seller,'{}');
 perform public.ingest_ebay_live_events(legacy,jsonb_build_array(obs),'{}');
 perform public.apply_ebay_live_stream_metadata(legacy,stream);
 perform pg_temp.verify((select sold_at='2026-08-24 04:15Z' from public.ebay_live_attempts where event_id=legacy),'original times backfill already matched observations');
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 begin perform public.correct_ebay_live_sale_sellers(event,array[auction],seller,'Unauthorized correction attempt.');raise exception 'Nonadmin correction accepted';exception when insufficient_privilege then null;end;
 perform pg_temp.verify(true,'seller corrections reject unauthorized users');
end $$;
rollback;
