begin;
set local statement_timeout='30s';
create or replace function pg_temp.verify(ok boolean,label text) returns void language plpgsql as $$
begin if ok is distinct from true then raise exception 'Failed: %',label;end if;raise notice 'ok %',label;end $$;
do $$
declare actor uuid:=(select user_id from public.employees where role='admin' and active is distinct from false limit 1);
 seller uuid:=(select id from public.employees where user_id=actor limit 1);
 event text:='RECOVER-'||replace(gen_random_uuid()::text,'-','');
 manual_event text:='RECOVER-'||replace(gen_random_uuid()::text,'-','');
 s public.live_sale_sessions;manual_s public.live_sale_sessions;recovery jsonb;recovery_state jsonb;health jsonb;
 obs jsonb:='{"key":"recovery-win","kind":"won","listing_id":"123456789012","title":"#001 - Recovery fixture","buyer":"recovery-fixture","amount":100,"currency":"USD","time_label":"12:15 AM","source":"activity"}';
 auction uuid;bag public.live_sale_lots;
begin
 perform set_config('request.jwt.claim.sub',actor::text,true);
 perform pg_temp.verify(not has_function_privilege('anon','public.complete_ebay_live_session(uuid,boolean,boolean,text)','execute'),'anonymous cannot close shows');
 perform pg_temp.verify(not has_function_privilege('authenticated','public.ebay_live_recovery_status(text)','execute'),'internal recovery summary is not directly callable');
 s:=public.start_ebay_live_capture(event,seller,'{}');
 recovery:=jsonb_build_object('protocol',1,'run_id',gen_random_uuid(),'phase','reading','sold_expected',0,'sold_seen',0,'observed_wins',0,'activity_passes',0,'listing_passes',0);
 health:=jsonb_build_object('observed_at',clock_timestamp(),'broadcast_ended',true,'pending',0,'recovery',recovery);
 perform public.ingest_ebay_live_events(event,'[]',health);
 recovery_state:=public.ebay_live_recovery_status(event);
 perform pg_temp.verify(recovery_state->>'phase'='reading' and recovery_state->>'can_close'='false','empty sync queue does not finish an unread history');
 begin perform public.complete_ebay_live_session(s.id,true,true);raise exception 'Closed during history reading';exception when invalid_parameter_value then null;end;
 perform pg_temp.verify((select status='active' from public.live_sale_sessions where id=s.id),'closing rechecks history on the server');
 perform public.ingest_ebay_live_events(event,'[]',health||jsonb_build_object('observed_at',clock_timestamp(),'recovery',recovery||'{"phase":"read","activity_passes":1,"listing_passes":2}'));
 perform pg_temp.verify(public.ebay_live_recovery_status(event)->>'phase'='needs_review','claim of completion needs both full passes');
 recovery:=recovery||'{"phase":"read","activity_passes":2,"listing_passes":2}';
 perform public.ingest_ebay_live_events(event,'[]',health||jsonb_build_object('observed_at',clock_timestamp(),'pending',4,'recovery',recovery));
 perform pg_temp.verify(public.ebay_live_recovery_status(event)->>'phase'='syncing','completed reading still waits for pending notifications');
 begin perform public.complete_ebay_live_session(s.id,true,true,'Checked manually against all eBay records.');raise exception 'Manual note bypassed sync';exception when invalid_parameter_value then null;end;
 perform pg_temp.verify(true,'manual history check cannot bypass unsent data');
 recovery:=recovery||'{"sold_expected":1,"sold_seen":1,"observed_wins":1}';
 perform public.ingest_ebay_live_events(event,'[]',health||jsonb_build_object('observed_at',clock_timestamp(),'recovery',recovery));
 perform pg_temp.verify(public.ebay_live_recovery_status(event)->>'phase'='needs_review','eBay listing seen without a saved auction still needs review');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs),health||jsonb_build_object('observed_at',clock_timestamp(),'recovery',recovery));
 recovery_state:=public.get_ebay_live_dashboard(s.id)->'recovery';
 perform pg_temp.verify(recovery_state->>'phase'='read' and (recovery_state->>'saved_auctions')::int=1 and (recovery_state->>'payment_issues')::int=1,'dashboard reports read history and separate payment issues');
 perform pg_temp.verify((select payment_state='waiting' from public.ebay_live_attempts where event_id=event),'history reading never confirms payment');
 begin perform public.complete_ebay_live_session(s.id,true,true);raise exception 'Read history bypassed unpaid sale';exception when invalid_parameter_value then null;end;
 perform pg_temp.verify(true,'completion retains payment and bag safeguards');
 select id into auction from public.ebay_live_attempts where event_id=event;
 perform public.resolve_ebay_live_attempt(auction,'cancel_release','Fixture only: no physical items in this auction.');
 perform public.ingest_ebay_live_events(event,'[]',health||jsonb_build_object('observed_at',clock_timestamp()-interval '10 minutes','recovery',recovery||'{"phase":"reading"}'));
 perform pg_temp.verify(public.ebay_live_recovery_status(event)->>'phase'='read','old heartbeat cannot overwrite newer recovery progress');
 perform public.complete_ebay_live_session(s.id,true,true);
 perform pg_temp.verify((select status='ended' from public.live_sale_sessions where id=s.id),'read and reconciled show can close');
 perform pg_temp.verify(exists(select 1 from public.ebay_live_audit where event_id=event and action='post_show_completed' and details#>>'{history_recovery,phase}'='read'),'final review records the recovery evidence');
 manual_s:=public.start_ebay_live_capture(manual_event,seller,'{}');
 perform public.ingest_ebay_live_events(manual_event,'[]',health||jsonb_build_object('observed_at',clock_timestamp(),'recovery',recovery||'{"phase":"paused"}'));
 begin perform public.complete_ebay_live_session(manual_s.id,true,true);raise exception 'Unchecked partial history closed';exception when invalid_parameter_value then null;end;
 perform pg_temp.verify(public.ebay_live_recovery_status(manual_event)->>'requires_manual_note'='true','interrupted history requires a documented comparison');
 perform public.complete_ebay_live_session(manual_s.id,true,true,'Compared full eBay history; fixture show contains no actual sales.');
 perform pg_temp.verify(exists(select 1 from public.ebay_live_audit where event_id=manual_event and action='post_show_completed' and details->>'manual_history_note' like 'Compared full%'),'manual fallback is recorded in the closing audit');
 perform pg_temp.verify(public.normalize_ebay_live_recovery('{"phase":"read","protocol":1}',now())->>'phase'='needs_review','malformed recovery cannot claim completion');
end $$;
rollback;
