begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
create temp table live_tap_results(result text);
do $checks$
declare
 actor uuid:=(select user_id from public.employees where role='admin' and active is distinct from false limit 1);
 seller uuid:=(select id from public.employees where user_id=actor limit 1);
 other uuid:=(select user_id from public.employees where user_id<>actor and active is distinct from false limit 1);
 sid uuid:=gen_random_uuid();event text:='TEST-'||replace(gen_random_uuid()::text,'-','');
 item uuid:=gen_random_uuid();loc uuid:=gen_random_uuid();stock uuid:=gen_random_uuid();rowid uuid;
 a uuid;b uuid;l public.live_sale_lots;obs jsonb;health jsonb:=jsonb_build_object('observed_at',now(),'ready',true);dash jsonb;ord uuid;line uuid; connected public.live_sale_sessions; before_count integer;
begin
 insert into live_tap_results select no_plan();
 insert into live_tap_results select ok(not has_function_privilege('anon','public.ingest_ebay_live_events(text,jsonb,jsonb)','EXECUTE'),'anonymous cannot ingest');
 insert into live_tap_results select ok(not has_table_privilege('authenticated','public.ebay_live_attempts','UPDATE'),'clients cannot mark a sale paid directly');
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 insert into live_tap_results select throws_ok(format('select public.get_ebay_live_dashboard(%L)',sid),'42501','Inventory access required','nonstaff denied');
 perform set_config('request.jwt.claim.sub',actor::text,true);
 insert into public.live_sale_sessions(id,title,primary_seller_employee_id) values(sid,'__live_test',seller);
 perform public.link_ebay_live_event(sid,event,seller);
 perform public.configure_ebay_live_event(event,seller,10,1,2);
 obs:=jsonb_build_object('key','win-1','kind','won','listing_id','123456789012','title','#001 - Test watch','buyer','testbuyer','amount',100,'currency','USD','ordinal','29','time_label','10:03 AM','source','activity','stream_offset_seconds',60);
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs),health);
 select id into a from public.ebay_live_attempts where event_id=event;
 insert into live_tap_results select is((select payment_state from public.ebay_live_attempts where id=a),'waiting','winning does not imply payment');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs),health);
 insert into live_tap_results select is((select count(*)::int from public.ebay_live_attempts where event_id=event),1,'duplicate win is idempotent');
 insert into live_tap_results select throws_ok(format('select public.claim_ebay_live_bag(%L)',a),'22023','Only a paid, open auction can be scanned','unpaid auction cannot be claimed');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"paid-1","kind":"paid","source":"listing"}'),health);
 l:=public.claim_ebay_live_bag(a);
 insert into live_tap_results select ok(l.auction_number like 'EB-001-%','bag uses displayed auction reference rather than tile position');
 insert into live_tap_results select is((public.claim_ebay_live_bag(a)).id,l.id,'claim retry reuses the same bag');
 insert into live_tap_results select throws_ok(format('select public.close_ebay_live_bag(%L)',a),'22023','Scan the sold item before closing the bag','empty bag cannot close');
 if other is not null then
  perform set_config('request.jwt.claim.sub',other::text,true);
  insert into live_tap_results select throws_ok(format('select public.claim_ebay_live_bag(%L)',a),'42501','Another scanner already has this bag. Ask an admin to release the claim','two scanners cannot claim the same bag');
  perform set_config('request.jwt.claim.sub',actor::text,true);
 end if;
 insert into public.item_types(id,title,barcode,cost,minimum_sale_price,sale_price) values(item,'__live_watch',gen_random_uuid()::text,40,60,150);
 insert into public.locations(id,location_name,location_code,active) values(loc,'__live_location',gen_random_uuid()::text,true);
 insert into public.item_stock_locations(id,item_id,location_id,quantity) values(stock,item,loc,10);
 insert into public.live_sale_lot_items(lot_id,session_id,item_id,source_stock_location_row_id,source_location_id,quantity) values(l.id,sid,item,stock,loc,1) returning id into rowid;
 insert into live_tap_results select ok((select live_unit_cost=40 and live_unit_minimum=60 from public.live_sale_lot_items where id=rowid),'scan snapshots cost and minimum');
 update public.item_types set cost=70,minimum_sale_price=80 where id=item;
 update public.live_sale_lot_items set quantity=2 where id=rowid;
 insert into live_tap_results select ok((select live_unit_cost=40 and live_unit_minimum=60 from public.live_sale_lot_items where id=rowid),'quantity correction retains original cost snapshot');
 update public.live_sale_lot_items set quantity=1 where id=rowid;
 perform public.close_ebay_live_bag(a);perform public.close_ebay_live_bag(a);
 dash:=public.get_ebay_live_dashboard(sid);
 insert into live_tap_results select is((dash#>>'{attempts,0,above_minimum}')::numeric,40::numeric,'above minimum is calculated separately');
 insert into live_tap_results select is((dash#>>'{attempts,0,estimated_profit}')::numeric,47::numeric,'estimated profit includes explicit fees and shipping');
 insert into live_tap_results select is((select quantity from public.item_stock_locations where id=stock),10,'scan and close only reserve physical stock');
 insert into live_tap_results select throws_ok(format('update public.live_sale_lot_items set quantity=2 where id=%L',rowid),'22023','Select a paid, open eBay auction before scanning','closed bag rejects more scans');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"failed-1","kind":"failed"}'),health);
 insert into live_tap_results select is((select status from public.live_sale_lot_items where id=rowid),'reserved','late failure holds stock until physical check');
 insert into live_tap_results select ok((public.get_ebay_live_dashboard(sid)#>>'{attempts,0,estimated_profit}') is null,'failed sale is removed from profit');
 insert into live_tap_results select throws_ok(format('update public.live_sale_lot_items set status=''packed'' where id=%L',rowid),'22023','Payment needs review before packing this bag','failed paid bag cannot be packed');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"paid-1","kind":"paid","source":"listing"}'),health);
 insert into live_tap_results select is((select payment_state from public.ebay_live_attempts where id=a),'failed','replayed paid badge cannot revive failure');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"paid-conflict","kind":"paid","source":"listing"}'),health);
 insert into live_tap_results select is((select payment_state from public.ebay_live_attempts where id=a),'review','conflicting new paid evidence requires review');
 perform public.resolve_ebay_live_attempt(a,'cancel_release','Verified eBay failure and removed the watch from this bag');
 insert into live_tap_results select is((select status from public.live_sale_lot_items where id=rowid),'cancelled','explicit physical review releases reservation');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"win-rerun","time_label":"10:05 AM"}'),health);
 select id into b from public.ebay_live_attempts where event_id=event and win_key='win-rerun';
 insert into live_tap_results select ok(a<>b,'rerun is a separate attempt');
 insert into live_tap_results select is((select payment_state from public.ebay_live_attempts where id=b),'waiting','rerun must establish its own payment');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"paid-1","kind":"paid","source":"listing"}'),health);
 insert into live_tap_results select is((select payment_state from public.ebay_live_attempts where id=b),'waiting','old paid receipt cannot pay rerun');
 perform public.resolve_ebay_live_attempt(b,'verify_paid','Verified the new transaction payment in eBay');
 update public.ebay_live_connections set capture_ready=false where event_id=event;
 l:=public.claim_ebay_live_bag(b);
 insert into live_tap_results select ok(l.id is not null,'recent audited verification allows disconnected scan');
 update public.ebay_live_attempts set verified_at=now()-interval '3 minutes' where id=b;
 insert into live_tap_results select throws_ok(format('select public.claim_ebay_live_bag(%L)',b),'22023','Capture is disconnected. Verify payment on eBay first','expired verification cannot override stale capture');
 perform public.ingest_ebay_live_events(event,jsonb_build_array('{"key":"unknown","kind":"unknown","source":"activity","evidence":"unrecognized payment event"}'::jsonb),health);
 insert into live_tap_results select ok((select not capture_ready from public.ebay_live_connections where event_id=event),'unrecognized evidence pauses automatic scans');
 perform public.resolve_ebay_live_observation(event,'unknown',null,'Checked eBay: unrelated notification, no auction affected');
 perform public.ingest_ebay_live_events(event,'[]',health);
 insert into live_tap_results select ok((select capture_ready from public.ebay_live_connections where event_id=event),'reviewed notifications allow capture to resume');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"new-order-win","listing_id":"222222222222","buyer":"differentbuyer"}'),health);
 select id into b from public.ebay_live_attempts where event_id=event and win_key='new-order-win';
 insert into public.ebay_orders(order_number,buyer_username,sale_date,raw_payload) values('__test_'||gen_random_uuid(),'differentbuyer',now(),'{"orderPaymentStatus":"PAID"}') returning id into ord;
 insert into public.ebay_order_lines(order_id,item_number,transaction_id,item_title,sold_for) values(ord,'222222222222','test','__live_test',100) returning id into line;
 perform public.reconcile_ebay_live_orders(event);
 insert into live_tap_results select ok((select payment_state='paid' and order_line_id=line from public.ebay_live_attempts where id=b),'unique official order reconciles payment');
 update public.ebay_orders set status='cancelled' where id=ord;
 perform public.reconcile_ebay_live_orders(event);
 insert into live_tap_results select is((select payment_state from public.ebay_live_attempts where id=b),'cancelled','later official cancellation stops the sale');

 -- Manual/general items use the same payment gate, but missing cost must stay unknown.
 perform public.resolve_ebay_live_attempt(b,'verify_paid','Verified corrected payment on eBay after cancellation review');
 l:=public.claim_ebay_live_bag(b);
 insert into public.live_sale_manual_lot_items(lot_id,session_id,item_category,item_description,quantity) values(l.id,sid,'Watch','Uncatalogued watch',1);
 perform public.close_ebay_live_bag(b);
 insert into live_tap_results select ok((select (x->>'estimated_profit') is null from jsonb_array_elements(public.get_ebay_live_dashboard(sid)->'attempts') x where x->>'id'=b::text),'manual items do not fabricate cost/profit');
 update public.ebay_orders set status='pending',raw_payload='{"orderPaymentStatus":"PARTIALLY_REFUNDED"}' where id=ord;
 insert into live_tap_results select is((select payment_state from public.ebay_live_attempts where id=b),'review','order import trigger catches later refunds without a dashboard visit');
 insert into live_tap_results select ok((select status='reserved' from public.live_sale_manual_lot_items where lot_id=l.id),'refund keeps manual bag contents for review');
 insert into live_tap_results select ok(not has_function_privilege('authenticated','public.reconcile_ebay_live_orders_internal(text)','EXECUTE'),'internal reconciliation has no client execution grant');
 -- eBay setup has no starting bag and linking is one transaction.
 connected:=public.start_ebay_live_session('__automatic_test',null,event||'AUTO',seller);
 insert into live_tap_results select is(connected.workflow_mode,'ebay_live','new show is explicitly automatic');
 insert into live_tap_results select is((select count(*)::int from public.live_sale_lots where session_id=connected.id),0,'automatic show creates no premature bag');
 insert into live_tap_results select ok(exists(select 1 from public.ebay_live_connections where session_id=connected.id),'new show is linked atomically');
 select count(*) into before_count from public.live_sale_sessions;
 insert into live_tap_results select throws_ok(format('select public.start_ebay_live_session(''__invalid_test'',null,%L,%L)',event,seller),'22023','This event is already linked to another show','duplicate event cannot start a second show');
 insert into live_tap_results select is((select count(*)::int from public.live_sale_sessions),before_count,'failed connection does not leave an orphan show');
 -- Failure notifications may be read before their win row in a virtualized feed.
 obs:=obs||'{"listing_id":"333333333333","buyer":"sequencebuyer","time_label":"11:28 AM"}';
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"failure-first","kind":"failed"}'),health);
 select id into a from public.ebay_live_attempts where event_id=event and listing_id='333333333333';
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"win-after-failure","kind":"won"}'),health);
 insert into live_tap_results select is((select count(*)::int from public.ebay_live_attempts where event_id=event and listing_id='333333333333'),1,'failure followed by matching win does not create duplicate');
 insert into live_tap_results select ok((select win_key='win-after-failure' and payment_state='failed' from public.ebay_live_attempts where id=a),'attaching win never revives payment failure');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"paid-after-failure","kind":"paid","source":"listing"}'),health);
 insert into live_tap_results select is((select payment_state from public.ebay_live_attempts where id=a),'review','contradictory paid badge requires verification');
 insert into live_tap_results select ok((select capture_ready from public.ebay_live_connections where event_id=event),'known failed auction does not stop unrelated sales');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"win-different-time","time_label":"11:31 AM"}'),health);
 insert into live_tap_results select is((select count(*)::int from public.ebay_live_attempts where event_id=event and listing_id='333333333333'),2,'distinct win is not collapsed into failed attempt');
 perform public.ingest_ebay_live_events(event,jsonb_build_array('{"key":"unidentified-win","kind":"won","source":"activity","title":"Still loading"}'::jsonb),health);
 dash:=public.get_ebay_live_dashboard(sid);
 insert into live_tap_results select ok((dash#>>'{connection,capture_ready}')::boolean,'missing win metadata does not stop other paid sales');
 insert into live_tap_results select ok(exists(select 1 from jsonb_array_elements(dash->'unmatched') x where x->>'source_key'='unidentified-win' and x->>'blocking'='false'),'dashboard distinguishes harmless metadata from payment risk');
 -- A combined capture artifact must not obstruct an exact official order match.
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"merged-order-win","listing_id":"444444444444","buyer":"mergebuyer"}'),health);
 select id into b from public.ebay_live_attempts where event_id=event and win_key='merged-order-win';
 insert into public.ebay_live_attempts(event_id,listing_id,listing_title,buyer,amount,payment_state,resolved_at,merged_into) values(event,'444444444444','Merged artifact','mergebuyer',100,'review',now(),b);
 insert into public.ebay_orders(order_number,buyer_username,sale_date,raw_payload) values('__test_'||gen_random_uuid(),'mergebuyer',now(),'{"orderPaymentStatus":"PAID"}') returning id into ord;
 insert into public.ebay_order_lines(order_id,item_number,transaction_id,item_title,sold_for) values(ord,'444444444444','test','__live_test',100) returning id into line;
 perform public.reconcile_ebay_live_orders(event);
 insert into live_tap_results select ok((select order_line_id=line and payment_state='paid' from public.ebay_live_attempts where id=b),'merged artifact does not prevent official reconciliation');
 insert into live_tap_results select is((select count(*)::int from jsonb_array_elements(public.get_ebay_live_dashboard(sid)->'attempts') x where x->>'listing_id'='444444444444'),1,'merged duplicate is hidden from queue');
 -- A notification with missing identity blocks the whole automatic queue, not a guessed buyer.
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"failure-without-buyer","kind":"failed","buyer":""}'),health);
 insert into live_tap_results select ok((select not capture_ready from public.ebay_live_connections where event_id=event),'payment failure missing its buyer stops auto scanning');
 update public.live_sale_sessions set status='ended',ended_at=now() where id=sid;
 insert into live_tap_results select throws_ok(format('select public.ingest_ebay_live_events(%L,''[]'')',event),'22023','This show has ended','ended shows cannot keep capturing new auctions');
 insert into live_tap_results select * from finish();
end $checks$;
select result from live_tap_results;
rollback;
