begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
create temp table post_tap_results(result text);
do $post_checks$
declare
 actor uuid:=(select user_id from public.employees where role='admin' and active is distinct from false limit 1);
 seller uuid:=(select id from public.employees where user_id=actor limit 1);
 event text:='POST-'||replace(gen_random_uuid()::text,'-','');
 show public.live_sale_sessions;l public.live_sale_lots;orphan public.live_sale_lots;m public.live_sale_manual_lot_items;
 a uuid;b uuid;obs jsonb;checks jsonb;ended timestamptz;
begin
 insert into post_tap_results select no_plan();
 perform set_config('request.jwt.claim.sub',actor::text,true);
 insert into post_tap_results select ok(not has_function_privilege('anon','public.complete_ebay_live_session(uuid,boolean,boolean)','EXECUTE'),'anonymous cannot close a session');
 insert into post_tap_results select ok(not has_table_privilege('authenticated','public.ebay_live_connections','UPDATE'),'clients cannot forge review completion');
 show:=public.start_ebay_live_session('__post_show_test',null,event,seller);
 obs:=jsonb_build_object('key','won','kind','won','listing_id','777777777771','title','Post-show watch','buyer','reviewbuyer','amount',150,'currency','USD','time_label','12:00 PM','source','activity','observed_at',clock_timestamp());
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs,obs||'{"key":"paid","kind":"paid"}'),jsonb_build_object('observed_at',clock_timestamp(),'ready',false));
 select id into a from public.ebay_live_attempts where event_id=event and win_key='won';
 insert into post_tap_results select throws_ok(format('select public.claim_ebay_live_bag(%L)',a),'22023','Capture is disconnected. Verify payment on eBay first','stalled capture alone does not end the broadcast');
 insert into post_tap_results select throws_ok(format('select public.complete_ebay_live_session(%L,true,true)',show.id),'22023','Mark the broadcast ended before closing the session','cannot complete a broadcasting show');
 perform public.ingest_ebay_live_events(event,'[]',jsonb_build_object('observed_at',clock_timestamp(),'ready',false,'broadcast_ended',true));
 select broadcast_ended_at into ended from public.ebay_live_connections where event_id=event;
 insert into post_tap_results select ok(ended is not null,'explicit eBay ended signal starts review');
 insert into post_tap_results select is((select status from public.live_sale_sessions where id=show.id),'active','ending broadcast leaves session open');
 perform public.ingest_ebay_live_events(event,'[]',jsonb_build_object('observed_at',clock_timestamp(),'ready',false,'broadcast_ended',false));
 perform public.mark_ebay_live_broadcast_ended(event);
 insert into post_tap_results select is((select broadcast_ended_at from public.ebay_live_connections where event_id=event),ended,'old heartbeat and repeated end do not revert or move end time');
 l:=public.claim_ebay_live_bag(a);
 m:=public.save_live_sale_manual_item(l.id,gen_random_uuid(),'Watch','Found after show',1,80,null,null);
 insert into post_tap_results select ok(m.id is not null,'post-show manual scanning works without live clock');
 insert into post_tap_results select throws_ok(format('select public.end_live_sale_session(%L)',show.id),'22023','Use the post-show checklist to close this eBay session','legacy end button cannot bypass checklist');
 insert into post_tap_results select throws_ok(format('select public.complete_ebay_live_session(%L,true,true)',show.id),'22023','Finish all paid bags and resolve outstanding payments, notifications and unlinked bags before closing','unfinished paid bag blocks closure');
 perform public.close_ebay_live_bag(a);
 insert into post_tap_results select ok((select closed_at is not null from public.ebay_live_attempts where id=a),'post-show paid bag closes without live clock');
 l:=public.reopen_ebay_live_bag(a);
 insert into post_tap_results select ok(l.closed_at is null and (select closed_at is null from public.ebay_live_attempts where id=a),'closed bag can reopen for missing items');
 insert into post_tap_results select is((select seller_id from public.ebay_live_attempts where id=a),seller,'reopening preserves seller attribution');
 m:=public.save_live_sale_manual_item(l.id,m.id,'Watch','Corrected physical bag',2,80,null,m.edit_revision);
 insert into post_tap_results select is(m.quantity,2,'worker can correct quantity after reopening');
 perform public.close_ebay_live_bag(a);
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"unidentified","kind":"failed","listing_id":null,"buyer":""}'),jsonb_build_object('ready',false));
 insert into post_tap_results select throws_ok(format('select public.reopen_ebay_live_bag(%L)',a),'22023','Verify payment before reopening this bag','unidentified payment failure blocks post-show scans');
 insert into post_tap_results select throws_ok(format('select public.complete_ebay_live_session(%L,true,true)',show.id),'22023','Finish all paid bags and resolve outstanding payments, notifications and unlinked bags before closing','unmatched payment evidence blocks final closure');
 perform public.resolve_ebay_live_observation(event,'unidentified',null,'Test notification checked against final eBay record');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||'{"key":"second-win","listing_id":"777777777772","buyer":"secondbuyer"}'),jsonb_build_object('ready',false));
 select id into b from public.ebay_live_attempts where event_id=event and win_key='second-win';
 insert into post_tap_results select is((public.get_ebay_live_dashboard(show.id)#>>'{post_show,payment_issues}')::int,1,'waiting payment appears on the final checklist');
 insert into post_tap_results select throws_ok(format('select public.claim_ebay_live_bag(%L)',b),'22023','Only a paid, open auction can be scanned','ended show never makes unpaid auctions scannable');
 perform public.resolve_ebay_live_attempt(b,'cancel_release','Verified unpaid order cancelled on eBay for test');
 orphan:=public.create_live_sale_lot(show.id,'UNLINKED-TEST',null,null,seller);
 insert into post_tap_results select is((public.get_ebay_live_dashboard(show.id)#>>'{post_show,unlinked_bags}')::int,1,'unlinked bags are not silently ignored');
 perform public.cancel_live_sale_lot(orphan.id,'Test empty stray bag reviewed',null);
 insert into post_tap_results select throws_ok(format('select public.complete_ebay_live_session(%L,false,true)',show.id),'22023','Confirm the physical bags and the final eBay payment review','worker must confirm physical check');
 update public.ebay_live_connections set health='{"pending":"1"}' where event_id=event;
 insert into post_tap_results select throws_ok(format('select public.complete_ebay_live_session(%L,true,true)',show.id),'22023','The capture helper still has pending notifications. Let them sync before closing','unsynced evidence blocks final closure');
 update public.ebay_live_connections set health='{"pending":"0"}' where event_id=event;
 perform public.complete_ebay_live_session(show.id,true,true);
 insert into post_tap_results select is((select status from public.live_sale_sessions where id=show.id),'ended','explicit checked completion ends inventory session');
 insert into post_tap_results select is((select review_completed_by from public.ebay_live_connections where event_id=event),actor,'reviewing worker recorded');
 insert into post_tap_results select ok(exists(select 1 from public.ebay_live_audit where event_id=event and action='post_show_completed'),'final checklist completion audited');
 insert into post_tap_results select lives_ok(format('select public.complete_ebay_live_session(%L,true,true)',show.id),'retrying completion is idempotent');
 insert into post_tap_results select throws_ok(format('select public.reopen_ebay_live_bag(%L)',a),'22023','This session is already closed','closed session cannot accept bag changes');
 insert into post_tap_results select * from finish();
end $post_checks$;
select * from post_tap_results;
rollback;
