begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
create temp table draft_tap_results(result text);
do $draft_checks$
declare
 actor uuid:=(select user_id from public.employees where role='admin' and active is distinct from false limit 1);
 seller uuid:=(select id from public.employees where user_id=actor limit 1);
 ev1 text:='DRAFT-A-'||replace(gen_random_uuid()::text,'-','');
 ev2 text:='DRAFT-B-'||replace(gen_random_uuid()::text,'-','');
 s1 public.live_sale_sessions;s2 public.live_sale_sessions;saved public.live_sale_sessions;
 l1 public.live_sale_lots;l2 public.live_sale_lots;m1 public.live_sale_manual_lot_items;m2 public.live_sale_manual_lot_items;
 a1 uuid;a2 uuid;obs jsonb;stamp timestamptz;
begin
 insert into draft_tap_results select no_plan();
 perform set_config('request.jwt.claim.sub',actor::text,true);
 insert into draft_tap_results select ok(not has_function_privilege('anon','public.set_live_sale_session_draft(uuid,boolean)','EXECUTE'),'anonymous users cannot save or resume shows');
 s1:=public.start_ebay_live_session('__draft_show_one',null,ev1,seller);
 obs:=jsonb_build_object('key','won','kind','won','listing_id','888888888881','title','#012 - Test watch','buyer','firstwinner','amount',150,'currency','USD','source','activity','time_label','12:00 PM','observed_at',clock_timestamp());
 perform public.ingest_ebay_live_events(ev1,jsonb_build_array(obs,obs||'{"key":"paid","kind":"paid"}'),jsonb_build_object('observed_at',clock_timestamp(),'ready',true));
 select id into a1 from public.ebay_live_attempts where event_id=ev1 and win_key='won';
 l1:=public.claim_ebay_live_bag(a1);
 m1:=public.save_live_sale_manual_item(l1.id,gen_random_uuid(),'Watch','First show item',1,80,null,null);
 saved:=public.set_live_sale_session_draft(s1.id,true);stamp:=saved.saved_for_later_at;
 insert into draft_tap_results select ok(stamp is not null,'draft marker saved on the server');
 insert into draft_tap_results select is(saved.saved_for_later_by,actor,'saving worker recorded');
 insert into draft_tap_results select is(saved.status,'active','draft remains unfinished and editable');
 insert into draft_tap_results select ok((select broadcast_ended_at is null from public.ebay_live_connections where event_id=ev1),'saving a draft does not invent an eBay broadcast end');
 insert into draft_tap_results select is((public.set_live_sale_session_draft(s1.id,true)).saved_for_later_at,stamp,'saving again is idempotent');
 insert into draft_tap_results select is((select count(*)::int from public.live_sale_events where session_id=s1.id and event_type='session_saved_for_later'),1,'draft save audited once');
 s2:=public.start_ebay_live_session('__draft_show_two',null,ev2,seller);
 perform public.ingest_ebay_live_events(ev2,jsonb_build_array(obs||'{"buyer":"secondwinner"}',obs||'{"key":"paid","kind":"paid","buyer":"secondwinner"}'),jsonb_build_object('observed_at',clock_timestamp(),'ready',true));
 select id into a2 from public.ebay_live_attempts where event_id=ev2 and win_key='won';
 l2:=public.claim_ebay_live_bag(a2);
 m2:=public.save_live_sale_manual_item(l2.id,gen_random_uuid(),'Coin','Second show item',1,40,null,null);
 insert into draft_tap_results select isnt(s1.id,s2.id,'back-to-back shows have separate sessions');
 insert into draft_tap_results select isnt(l1.lot_code,l2.lot_code,'repeated auction numbers have distinct bag QR identifiers');
 insert into draft_tap_results select is((select buyer from public.ebay_live_attempts where id=a1),'firstwinner','first winner is retained');
 insert into draft_tap_results select is((select seller_id from public.ebay_live_attempts where id=a1),seller,'first seller credit is retained');
 insert into draft_tap_results select is((select live_unit_minimum from public.live_sale_manual_lot_items where id=m1.id),80::numeric,'first break-even price is retained');
 insert into draft_tap_results select is((select status from public.live_sale_manual_lot_items where id=m1.id),'reserved','draft does not release bag contents');
 insert into draft_tap_results select ok((select closed_at is null from public.ebay_live_attempts where id=a1),'draft does not close bags');
 perform public.ingest_ebay_live_events(ev1,'[]',jsonb_build_object('observed_at',clock_timestamp(),'ready',false,'broadcast_ended',true));
 insert into draft_tap_results select ok((select broadcast_ended_at is not null from public.ebay_live_connections where event_id=ev1),'saved show still accepts its late end notification');
 insert into draft_tap_results select throws_ok(format('select public.complete_ebay_live_session(%L,true,true)',s1.id),'22023','Finish all paid bags and resolve outstanding payments, notifications and unlinked bags before closing','draft does not bypass the final bag checklist');
 saved:=public.set_live_sale_session_draft(s1.id,false);
 insert into draft_tap_results select ok(saved.saved_for_later_at is null and saved.saved_for_later_by is null,'resume clears the draft marker');
 insert into draft_tap_results select ok(exists(select 1 from public.live_sale_events where session_id=s1.id and event_type='session_resumed'),'resume is audited');
 insert into draft_tap_results select is((public.claim_ebay_live_bag(a1)).id,l1.id,'resuming recovers the same unfinished bag');
 m1:=public.save_live_sale_manual_item(l1.id,m1.id,'Watch','Completed later',1,90,null,m1.edit_revision);
 insert into draft_tap_results select is(m1.live_unit_minimum,90::numeric,'resumed bag can be completed after the broadcast');
 perform public.close_ebay_live_bag(a1);
 perform public.complete_ebay_live_session(s1.id,true,true);
 insert into draft_tap_results select is((select status from public.live_sale_sessions where id=s1.id),'ended','saved show closes only after checks and bag completion');
 insert into draft_tap_results select throws_ok(format('select public.set_live_sale_session_draft(%L,false)',s1.id),'22023','This show is already closed or unavailable','resume cannot reopen a closed session');
 insert into draft_tap_results select is((select status from public.live_sale_sessions where id=s2.id),'active','finishing first show does not close the second');
 insert into draft_tap_results select is((select live_unit_minimum from public.live_sale_manual_lot_items where id=m2.id),40::numeric,'second bag remains unchanged');
 perform public.set_live_sale_session_draft(s2.id,true);
 perform public.ingest_ebay_live_events(ev2,jsonb_build_array(obs||'{"key":"late-failure","kind":"failed","buyer":"secondwinner"}'),jsonb_build_object('observed_at',clock_timestamp(),'ready',false));
 insert into draft_tap_results select is((select payment_state from public.ebay_live_attempts where id=a2),'failed','draft still receives late payment failure');
 perform set_config('request.jwt.claim.sub','',true);
 insert into draft_tap_results select throws_ok(format('select public.set_live_sale_session_draft(%L,false)',s2.id),'42501','Inventory access required','unauthenticated resume is rejected');
 insert into draft_tap_results select * from finish();
end $draft_checks$;
select * from draft_tap_results;
rollback;
