begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
create temp table manual_tap_results(result text);
do $manual_checks$
declare
 actor uuid:=(select user_id from public.employees where role='admin' and active is distinct from false limit 1);
 seller uuid:=(select id from public.employees where user_id=actor limit 1);
 next_seller uuid:=(select id from public.employees where id<>seller and active is distinct from false limit 1);
 event text:='MANUAL-'||replace(gen_random_uuid()::text,'-','');
 show public.live_sale_sessions;l public.live_sale_lots;m public.live_sale_manual_lot_items;n public.live_sale_manual_lot_items;
 a uuid;b uuid;c uuid;manual_id uuid:=gen_random_uuid();obs jsonb;health jsonb:=jsonb_build_object('observed_at',clock_timestamp(),'ready',true);dash jsonb;
 inventory uuid:=gen_random_uuid();loc uuid:=gen_random_uuid();stock uuid:=gen_random_uuid();early timestamptz;changed integer;
begin
 insert into manual_tap_results select no_plan();
 insert into manual_tap_results select ok(not has_function_privilege('anon','public.save_live_sale_manual_item(uuid,uuid,text,text,integer,numeric,text,integer)','EXECUTE'),'anonymous cannot change manual prices');
 insert into manual_tap_results select ok(not has_table_privilege('authenticated','public.ebay_live_seller_changes','INSERT'),'seller timeline is server controlled');
 perform set_config('request.jwt.claim.sub',actor::text,true);
 show:=public.start_ebay_live_session('__manual_seller_test',null,event,seller);
 obs:=jsonb_build_object('key','first-win','kind','won','listing_id','888888888881','title','Manual watch','buyer','manualbuyer','amount',150,'currency','USD','time_label','12:00 PM','source','activity','observed_at',clock_timestamp());
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs,obs||'{"key":"first-paid","kind":"paid"}'),health);
 select id into a from public.ebay_live_attempts where event_id=event and win_key='first-win';
 l:=public.claim_ebay_live_bag(a);
 m:=public.save_live_sale_manual_item(l.id,manual_id,'Watch','Test watch',2,50,null,null);
 insert into manual_tap_results select is(m.live_unit_minimum,50::numeric,'manual break-even saved per unit');
 insert into manual_tap_results select is((public.save_live_sale_manual_item(l.id,manual_id,'Watch','Test watch',2,50,null,null)).id,m.id,'retry reuses saved item instead of duplicating');
 insert into manual_tap_results select throws_ok(format('select public.save_live_sale_manual_item(%L,%L,''Watch'',''Test watch'',2,-1,null,1)',l.id,m.id),'22023','Enter a valid item, quantity and break-even price','negative break-even rejected');
 insert into manual_tap_results select throws_ok(format('select public.save_live_sale_manual_item(%L,%L,''Watch'',''Test watch'',2,50,''https://example.invalid/image.jpg'',1)',l.id,m.id),'22023','Invalid manual item photo','photo must belong to the manual upload path');
 m:=public.save_live_sale_manual_item(l.id,m.id,'Chain','Gold chain',2,60,'live-manual/'||l.id||'/'||m.id||'/'||gen_random_uuid()||'.jpg',m.edit_revision);
 insert into manual_tap_results select ok(m.edit_revision=2 and m.item_category='Chain' and m.photo_path is not null,'edit saves identity, minimum and photo together');
 insert into manual_tap_results select throws_ok(format('select public.save_live_sale_manual_item(%L,%L,''Watch'',''Old form'',2,50,null,1)',l.id,m.id),'40001','This item changed. Reopen Edit to load the latest details','stale editor cannot overwrite newer changes');
 n:=public.save_live_sale_manual_item(l.id,gen_random_uuid(),'Chain','Gold chain',1,10,null,null);
 insert into manual_tap_results select is((select count(*)::int from public.live_sale_manual_lot_items where lot_id=l.id),2,'same descriptions keep independent manual prices');
 dash:=public.get_ebay_live_dashboard(show.id);
 insert into manual_tap_results select is((dash#>>'{attempts,0,minimum_total}')::numeric,130::numeric,'manual quantity multiplies the unit minimum');
 insert into manual_tap_results select is((dash#>>'{attempts,0,units}')::int,3,'manual units count in the queue');
 n:=public.save_live_sale_manual_item(l.id,n.id,'Chain','Gold chain',1,null,null,n.edit_revision);
 insert into manual_tap_results select ok((public.get_ebay_live_dashboard(show.id)#>>'{attempts,0,minimum_total}') is null,'missing manual minimum stays unknown');
 n:=public.save_live_sale_manual_item(l.id,n.id,'Chain','Gold chain',1,10,null,n.edit_revision);
 insert into public.item_types(id,title,barcode,cost,minimum_sale_price,sale_price) values(inventory,'__mixed_test',gen_random_uuid()::text,25,40,80);
 insert into public.locations(id,location_name,location_code,active) values(loc,'__manual_location',gen_random_uuid()::text,true);
 insert into public.item_stock_locations(id,item_id,location_id,quantity) values(stock,inventory,loc,5);
 insert into public.live_sale_lot_items(lot_id,session_id,item_id,source_stock_location_row_id,source_location_id,quantity) values(l.id,show.id,inventory,stock,loc,1);
 perform public.close_ebay_live_bag(a);
 dash:=public.get_ebay_live_dashboard(show.id);
 insert into manual_tap_results select is((dash#>>'{attempts,0,minimum_total}')::numeric,170::numeric,'inventory and manual break-even prices combine');
 insert into manual_tap_results select is((dash#>>'{attempts,0,above_minimum}')::numeric,-20::numeric,'a loss below break-even is visible');
 insert into manual_tap_results select ok((dash#>>'{attempts,0,estimated_profit}') is null,'manual minimum is not invented as actual cost');
 insert into manual_tap_results select throws_ok(format('select public.save_live_sale_manual_item(%L,%L,''Chain'',''Gold chain'',1,60,null,2)',l.id,m.id),'22023','Select a paid, open eBay auction before editing','closed bag cannot be silently edited');
 insert into manual_tap_results select throws_ok(format('update public.live_sale_manual_lot_items set live_unit_minimum=1 where id=%L',m.id),'22023','Select a paid, open eBay auction before scanning','direct price writes cannot bypass the closed-bag guard');
 early:=clock_timestamp();
 perform public.set_ebay_live_seller(event,next_seller);
 insert into manual_tap_results select is((select seller_id from public.ebay_live_attempts where id=a),seller,'seller switch preserves earlier sales');
 insert into manual_tap_results select is((select owner_employee_id from public.live_sale_lots where id=l.id),seller,'seller switch preserves earlier bags');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||jsonb_build_object('key','next-win','listing_id','888888888882','observed_at',clock_timestamp())),health);
 select id into b from public.ebay_live_attempts where event_id=event and win_key='next-win';
 insert into manual_tap_results select is((select seller_id from public.ebay_live_attempts where id=b),next_seller,'next incoming auction belongs to the on-air seller');
 perform public.ingest_ebay_live_events(event,jsonb_build_array(obs||jsonb_build_object('key','delayed-win','listing_id','888888888883','observed_at',early)),health);
 select id into c from public.ebay_live_attempts where event_id=event and win_key='delayed-win';
 insert into manual_tap_results select is((select seller_id from public.ebay_live_attempts where id=c),seller,'queued evidence retains seller active when captured');
 changed:=public.set_ebay_live_seller(event,next_seller,true,'All sales in this show were made by the selected seller');
 insert into manual_tap_results select is(changed,2,'explicit correction updates only incorrectly attributed attempts');
 insert into manual_tap_results select ok(not exists(select 1 from public.ebay_live_attempts where event_id=event and seller_id<>next_seller),'explicit correction fixes all previous sale attribution');
 insert into manual_tap_results select is((select owner_employee_id from public.live_sale_lots where id=l.id),next_seller,'explicit correction also fixes closed bags');
 insert into manual_tap_results select is((select claimed_by from public.ebay_live_attempts where id=a),actor,'scanner identity remains separate from seller');
 insert into manual_tap_results select is((select primary_seller_employee_id from public.live_sale_sessions where id=show.id),next_seller,'show summary reflects corrected seller');
 insert into manual_tap_results select ok(exists(select 1 from public.ebay_live_audit where event_id=event and action='seller_corrected'),'seller corrections retain an audit trail');
 insert into manual_tap_results select is(public.ebay_live_seller_at(event,early),next_seller,'show-wide correction also covers delayed old evidence');
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 insert into manual_tap_results select throws_ok(format('select public.set_ebay_live_seller(%L,%L)',event,seller),'42501','Inventory access required','nonstaff cannot switch the seller');
 insert into manual_tap_results select * from finish();
end $manual_checks$;
select result from manual_tap_results;
rollback;
