begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
create temp table intake_results(result text);
do $checks$
declare
 actor uuid:=(select user_id from public.employees where role='admin' and active is distinct from false limit 1);
 seller uuid:=(select id from public.employees where user_id=actor limit 1);
 event text:='INTAKE-'||replace(gen_random_uuid()::text,'-','');
 unlinked_event text:='UPCOMING-'||replace(gen_random_uuid()::text,'-','');
 reserved_show uuid:=gen_random_uuid();show public.live_sale_sessions;job public.ebay_live_listing_requests;again public.ebay_live_listing_requests;
 inventory uuid:=gen_random_uuid();loc uuid:=gen_random_uuid();stock uuid:=gen_random_uuid();worker uuid:=gen_random_uuid();code text:='TEST-'||gen_random_uuid();bag public.live_sale_lots;
begin
 insert into intake_results select no_plan();
 insert into intake_results select ok(not has_table_privilege('authenticated','public.ebay_live_listing_requests','INSERT'),'clients cannot write queue directly');
 insert into intake_results select ok(not has_function_privilege('anon','public.queue_live_listing(uuid,text,text,numeric,integer,boolean)','EXECUTE'),'anonymous cannot queue');
 perform set_config('request.jwt.claim.sub',actor::text,true);
 show:=public.start_ebay_live_session('__listing_intake_test',null,event,seller);
 insert into intake_results select ok((select source_seen_at is null from public.ebay_live_connections where event_id=event),'preparation begins before capture or broadcast');
 insert into public.item_types(id,title,description,barcode,photos,cost,sale_price) values(inventory,'Test stock watch','Test public description',code,array['test/photo.jpg'],500,1000);
 insert into public.locations(id,location_name,location_code,active) values(loc,'__intake_test',gen_random_uuid()::text,true);
 insert into public.item_stock_locations(id,item_id,location_id,quantity,condition_status) values(stock,inventory,loc,2,'good');
 insert into intake_results select is((public.lookup_live_listing_item(code)->>'id')::uuid,inventory,'barcode resolves internal stock ID');
 insert into intake_results select is((public.lookup_live_listing_item(lower(code))->>'available')::int,2,'barcode is case insensitive');
 insert into intake_results select ok(not(public.lookup_live_listing_item(code)?'cost'),'private cost absent from lookup payload');
 insert into intake_results select throws_ok(format('select public.queue_live_listing(%L,%L,%L,0,30,false)',gen_random_uuid(),event,code),'P0001','Enter a starting bid and auction duration','zero bid rejected');
 insert into intake_results select throws_ok(format('select public.queue_live_listing(%L,%L,%L,1,2,false)',gen_random_uuid(),event,code),'P0001','Enter a starting bid and auction duration','invalid duration rejected');
 update public.item_types set photos='{}' where id=inventory;
 insert into intake_results select throws_ok(format('select public.queue_live_listing(%L,%L,%L,1,30,false)',gen_random_uuid(),event,code),'P0001','This item needs 1–25 stock photos','missing photos rejected on server');
 update public.item_types set photos=array['test/photo.jpg'] where id=inventory;
 job:=public.queue_live_listing(gen_random_uuid(),event,code,1,30,true);
 again:=public.queue_live_listing(gen_random_uuid(),event,code,5,60,true);
 insert into intake_results select is(again.id,job.id,'repeat scan reuses same request');
 insert into intake_results select is(again.starting_bid,1::numeric,'repeat scan cannot silently change chosen bid');
 again:=public.claim_live_listing(event,worker);
 insert into intake_results select is(again.status,'preparing','computer claims queued item');
 insert into intake_results select is((public.claim_live_listing(event,worker)).id,job.id,'same computer resumes claim');
 insert into intake_results select throws_ok(format('select public.claim_live_listing(%L,%L)',event,gen_random_uuid()),'P0001','An item is already being prepared on another receiver. Finish it there first.','second computer cannot fill duplicate form');
 insert into intake_results select throws_ok(format('select public.report_live_listing(%L,%L,''ready'')',job.id,gen_random_uuid()),'42501','This preparation belongs to another computer','wrong worker cannot report');
 insert into intake_results select throws_ok(format('select public.report_live_listing(%L,%L,''created'',null,''999999999999'')',job.id,worker),'P0001','This preparation has already changed. Refresh its status.','cannot confirm before form is ready');
 perform public.report_live_listing(job.id,worker,'ready');
 insert into intake_results select throws_ok(format('select public.report_live_listing(%L,%L,''created'',null,''oops'')',job.id,worker),'P0001','A verified eBay listing ID is required','invalid listing ID rejected');
 perform public.report_live_listing(job.id,worker,'created',null,'999999999999');
 perform public.report_live_listing(job.id,worker,'created',null,'999999999999');
 insert into intake_results select is((public.get_live_listing_requests(event)->0->>'status'),'created','phone receives completion');
 insert into intake_results select is((select quantity from public.item_stock_locations where id=stock),2,'preparation does not deduct stock');
 insert into intake_results select is((select count(*)::int from public.ebay_live_attempts where event_id=event),0,'preparation creates no paid sales');
 insert into public.live_sale_sessions(id,title) values(reserved_show,'__intake_reservation_test');
 insert into public.live_sale_lots(session_id,auction_number) values(reserved_show,'test') returning * into bag;
 insert into public.live_sale_lot_items(lot_id,session_id,item_id,source_stock_location_row_id,source_location_id,quantity,status) values(bag.id,reserved_show,inventory,stock,loc,2,'reserved');
 insert into intake_results select is((public.lookup_live_listing_item(code)->>'available')::int,0,'bag reservations excluded from available stock');
 update public.ebay_live_listing_requests set status='queued',worker_id=null,worker_token=null where id=job.id;
 again:=public.claim_live_listing(event,worker);
 insert into intake_results select ok(again.id is null,'reserved stock cannot be prepared');
 insert into intake_results select is((select status from public.ebay_live_listing_requests where id=job.id),'failed','unavailable stock shown as failure');
 update public.item_types set description='Corrected saved description' where id=inventory;
 perform public.retry_live_listing(job.id);
 insert into intake_results select is((select snapshot->>'description' from public.ebay_live_listing_requests where id=job.id),'Corrected saved description','retry refreshes corrected stock data');
 update public.ebay_live_connections set broadcast_ended_at=now() where event_id=event;
 delete from public.live_sale_lot_items where lot_id=bag.id;
 again:=public.claim_live_listing(event,worker);
 insert into intake_results select is(again.status,'preparing','broadcast ending does not block preparation');
 delete from public.ebay_live_listing_requests where id=job.id;
 update public.ebay_live_connections set review_completed_at=now() where event_id=event;
 update public.live_sale_sessions set status='ended',ended_at=now() where id=show.id;
 job:=public.queue_live_listing(gen_random_uuid(),event,code,1,30,true);
 insert into intake_results select is(job.status,'queued','completed show accepts a new preparation');
 again:=public.claim_live_listing(event,worker);
 insert into intake_results select is(again.status,'preparing','completed show preparation can be claimed');
 insert into intake_results select is((select status from public.live_sale_sessions where id=show.id),'ended','preparation never reopens the sales session');
 insert into intake_results select ok((select broadcast_ended_at=now() and review_completed_at=now() from public.ebay_live_connections where event_id=event),'preparation preserves completed broadcast and review');
 again:=public.claim_live_listing(unlinked_event,worker);
 insert into intake_results select ok(again.id is null,'new event with no queue is empty, not incorrectly ended');
 job:=public.queue_live_listing(gen_random_uuid(),unlinked_event,code,2,60,true);
 insert into intake_results select is(job.status,'queued','event without any Invsto show can queue');
 again:=public.queue_live_listing(gen_random_uuid(),unlinked_event,code,5,30,true);
 insert into intake_results select is(again.id,job.id,'unlinked event duplicate scans still reuse the request');
 again:=public.claim_live_listing(unlinked_event,worker);
 insert into intake_results select is(again.status,'preparing','unlinked event request can be claimed');
 insert into intake_results select throws_ok(format('select public.claim_live_listing(%L,%L)',unlinked_event,gen_random_uuid()),'P0001','An item is already being prepared on another receiver. Finish it there first.','unlinked event still prevents a second computer claim');
 insert into intake_results select is((select count(*)::int from public.ebay_live_connections where event_id=unlinked_event),0,'preparation does not create a capture connection');
 insert into intake_results select is((select quantity from public.item_stock_locations where id=stock),2,'independent preparation does not change stock');
 insert into intake_results select throws_ok(format('select public.claim_live_listing(%L,%L)','https://wrong.example',worker),'22023','Enter a valid eBay Stream Manager event URL','claim validates destination ID');
 insert into intake_results select throws_ok(format('select public.queue_live_listing(%L,%L,%L,1,30,true)',gen_random_uuid(),'bad',code),'22023','Enter a valid eBay Stream Manager event URL','queue validates destination ID');
 perform set_config('request.jwt.claim.sub','',true);
 insert into intake_results select throws_ok(format('select public.lookup_live_listing_item(%L)',code),'42501','Inventory access required','unauthenticated lookup rejected');
 insert into intake_results select * from finish();
end $checks$;
select * from intake_results;
do $$declare r record;begin for r in select result from intake_results loop raise notice '%',r.result;end loop;if exists(select 1 from intake_results where result like 'not ok%') then raise exception 'Intake regression test failed';end if;end $$;
rollback;
