begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(27);
select ok(not has_table_privilege('anon','public.print_stations','SELECT'),'anonymous clients cannot read station credentials');
select ok(not has_table_privilege('authenticated','public.label_print_jobs','SELECT'),'staff cannot bypass job RPC validation');
select ok(not has_function_privilege('anon','public.enqueue_label_print(uuid,uuid,text,integer,text,text,uuid)','EXECUTE'),'anonymous callers cannot enqueue');
select ok(not has_function_privilege('anon','public._print_station_authorize(uuid,text)','EXECUTE'),'station auth helper is private');
select set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
select throws_ok('select public.list_print_stations()','42501','Inventory access required','non-staff cannot list stations');
select set_config('request.jwt.claim.sub',(select user_id::text from public.employees where role='admin' and active is distinct from false limit 1),true);
create temp table print_test_values(key text primary key,value jsonb);
insert into print_test_values values('a',public.register_print_station('__print_test_a_'||gen_random_uuid()::text)),('b',public.register_print_station('__print_test_b_'||gen_random_uuid()::text));
select is((select count(*)::int from print_test_values),2,'two independent stations registered');
select lives_ok($$select public.pair_print_station((select value->>'code' from print_test_values where key='a'),repeat('a',64),'Computer A','DYMO A','450')$$,'pair station A');
select lives_ok($$select public.pair_print_station((select value->>'code' from print_test_values where key='a'),repeat('a',64),'Computer A','DYMO A','450')$$,'pairing is safe to retry with the same token');
select throws_ok($$select public.pair_print_station((select value->>'code' from print_test_values where key='a'),repeat('c',64),'Other','DYMO A','450')$$,'42501','Pairing code already used','pairing cannot be stolen after use');
select lives_ok($$select public.pair_print_station((select value->>'code' from print_test_values where key='b'),repeat('b',64),'Computer B','DYMO B','450')$$,'pair station B');
select throws_ok($$select public.poll_print_station((select (value->>'station_id')::uuid from print_test_values where key='b'),repeat('a',64),true)$$,'42501','Print station is not paired or has been disconnected','station A credential cannot claim from B');
select ok(public.list_print_stations()::text not like '%token_hash%','station listing excludes credentials');
insert into print_test_values values('request',to_jsonb(gen_random_uuid()::text));
insert into print_test_values values('job',public.enqueue_label_print((select (value->>'station_id')::uuid from print_test_values where key='a'),(select (value#>>'{}')::uuid from print_test_values where key='request'),'<DesktopLabel Version="1"></DesktopLabel>',2,'Test label'));
select is(public.enqueue_label_print((select (value->>'station_id')::uuid from print_test_values where key='a'),(select (value#>>'{}')::uuid from print_test_values where key='request'),'<DesktopLabel Version="1"></DesktopLabel>',2)->>'id',(select value->>'id' from print_test_values where key='job'),'retrying enqueue returns the same job');
select throws_ok($$select public.enqueue_label_print((select (value->>'station_id')::uuid from print_test_values where key='b'),(select (value#>>'{}')::uuid from print_test_values where key='request'),'<DesktopLabel Version="1"></DesktopLabel>',2)$$,'P0001','This print request already has a different destination or content','a retry never reroutes');
select is(public.poll_print_station((select (value->>'station_id')::uuid from print_test_values where key='b'),repeat('b',64),true),null::jsonb,'other station sees no job');
select is(public.poll_print_station((select (value->>'station_id')::uuid from print_test_values where key='a'),repeat('a',64),false),null::jsonb,'disconnected printer leaves job queued');
insert into print_test_values values('claim',public.poll_print_station((select (value->>'station_id')::uuid from print_test_values where key='a'),repeat('a',64),true));
select is((select value->>'id' from print_test_values where key='claim'),(select value->>'id' from print_test_values where key='job'),'selected station claims its own job');
select is(public.poll_print_station((select (value->>'station_id')::uuid from print_test_values where key='a'),repeat('a',64),true),null::jsonb,'a second poll cannot reclaim an active job');
select throws_ok($$select public.report_label_print((select (value->>'station_id')::uuid from print_test_values where key='b'),repeat('b',64),(select (value->>'id')::uuid from print_test_values where key='claim'),(select (value->>'claim_token')::uuid from print_test_values where key='claim'),'submitted',2)$$,'42501','Print claim does not belong to this station','other station cannot acknowledge a job');
select throws_ok($$select public.cancel_label_print((select (value->>'id')::uuid from print_test_values where key='claim'))$$,'P0001','This job has already been picked up. It cannot be cancelled safely.','claimed jobs cannot be silently cancelled');
update public.label_print_jobs set lease_until=now()-interval '1 minute' where id=(select (value->>'id')::uuid from print_test_values where key='claim');
select is(public.poll_print_station((select (value->>'station_id')::uuid from print_test_values where key='a'),repeat('a',64),true),null::jsonb,'expired job is not replayed');
select is((select status from public.label_print_jobs where id=(select (value->>'id')::uuid from print_test_values where key='claim')),'uncertain','expired claim needs physical review');
select is(public.report_label_print((select (value->>'station_id')::uuid from print_test_values where key='a'),repeat('a',64),(select (value->>'id')::uuid from print_test_values where key='claim'),(select (value->>'claim_token')::uuid from print_test_values where key='claim'),'submitted',2)->>'status','submitted','durable acknowledgement can recover after a lost connection');
select is(public.report_label_print((select (value->>'station_id')::uuid from print_test_values where key='a'),repeat('a',64),(select (value->>'id')::uuid from print_test_values where key='claim'),(select (value->>'claim_token')::uuid from print_test_values where key='claim'),'submitted',2)->>'status','submitted','repeated acknowledgement is idempotent');
select throws_ok($$select public.enqueue_label_print((select (value->>'station_id')::uuid from print_test_values where key='a'),gen_random_uuid(),'<DesktopLabel/>',101)$$,'P0001','Choose between 1 and 100 copies','copies bounded');
select public.disconnect_print_station((select (value->>'station_id')::uuid from print_test_values where key='a'));
select throws_ok($$select public.poll_print_station((select (value->>'station_id')::uuid from print_test_values where key='a'),repeat('a',64),true)$$,'42501','Print station is not paired or has been disconnected','revocation invalidates the helper credential');
select ok(not exists(select 1 from public.print_stations where id=(select (value->>'station_id')::uuid from print_test_values where key='a') and active),'disconnected station is inactive');
select * from finish();
rollback;
