/* Packaging uses the existing private task evidence bucket and task assignment RPC.
   All fulfillment, quantity and dispatch decisions remain server-authoritative. */
(() => {
 'use strict';
 const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const media=window.OGPackagingMedia.create({signed:(p,force)=>signed(p,force)});
 const views=[['to_package','To package'],['in_progress','In progress'],['on_hold','On hold'],['sending','Sending today'],['history','History']];
 const labels={in_progress:'In progress',on_hold:'On hold',ready:'Sending today',dispatched:'Dispatched',cancelled:'Cancelled'};
 const state={client:null,user:null,admin:false,view:'to_package',search:'',offset:0,queue:null,detail:null,buyerOrder:null,busy:false,dirty:false,uploads:[],staff:null,read:0,requests:new Map(),urls:new Map()};
 const date=v=>v?new Date(v).toLocaleString(undefined,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'—';
 const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const message=(text,error=false)=>{$('pack-status').innerHTML=text?`<div class="pack-notice ${error?'error':'success'}">${esc(text)}</div>`:'';};
 async function rpc(action,args={}) {const {data,error}=await state.client.rpc('packaging_workspace',{_action:action,_args:args});if(error)throw Error(error.message||'Could not save. Please retry.');return data;}
 function busy(value){state.busy=value;document.querySelectorAll('.packaging-page button,.packaging-page input,.pack-dialog button,.pack-dialog input,.pack-dialog textarea,.pack-dialog select').forEach(b=>{if(value){if(b.dataset.wasDisabled===undefined)b.dataset.wasDisabled=String(b.disabled);b.disabled=true;}else if(b.dataset.wasDisabled!==undefined){b.disabled=b.dataset.wasDisabled==='true';delete b.dataset.wasDisabled;}});}
 function hasClaim(){const s=state.detail?.shipment;return s&&s.claimed_by===state.user&&new Date(s.claimed_until)>new Date();}
 function editable(){return ['in_progress','on_hold'].includes(state.detail?.shipment?.status)&&hasClaim();}
 function canLeave(){return !state.busy&&(!state.dirty&&!state.uploads.length||window.confirm('There are unsaved quantities or uploads. Leave this package and discard those local changes?'));}
 async function queue(){const ticket=++state.read;const data=await rpc('queue',{view:state.view,search:state.search,offset:state.offset});if(ticket!==state.read)return;state.queue=data;state.user=data.user_id;state.admin=data.is_admin;renderQueue();}
 function renderQueue(){const q=state.queue;if(!q)return;
  $('pack-tabs').innerHTML=views.map(([key,label])=>`<button type="button" data-view="${key}" aria-current="${state.view===key}">${label}<b>${q.counts[key]||0}</b></button>`).join('');
  $('pack-queue-title').textContent=views.find(v=>v[0]===state.view)[1];$('pack-total').textContent=`${q.total} ${state.view==='to_package'?(q.total===1?'buyer':'buyers'):(q.total===1?'package':'packages')}`;
  $('pack-list').innerHTML=!q.enabled?'<div class="pack-empty"><strong>Packaging is being prepared</strong>Newly closed orders will appear here once the handoff is activated.</div>':!q.rows.length?`<div class="pack-empty"><strong>${state.search?'No matches':'All clear here'}</strong>${state.search?'Try a buyer, order or tracking number.':state.view==='to_package'?'Newly closed orders will appear here. Earlier order history stays in Order History.':'There are no packages in this queue.'}</div>`:q.rows.map(r=>`<button type="button" class="pack-row ${r.shipment_id?r.shipment_id===state.detail?.shipment?.id?'selected':'':state.buyerOrder===r.order_id?'selected':''}" data-package="${esc(r.shipment_id||'')}" data-order="${esc(r.order_id||'')}" data-buyer-order="${esc(r.buyer_key?r.order_id:'')}"><small>${r.shipment_id?'PACKAGE':'BUYER · READY TO PACKAGE'}${r.carryover?' · <b class="carryover">Carried over</b>':''}</small><strong>${esc(r.title)}</strong><span>${esc(r.subtitle)}</span><small>${date(r.created_at)} <span aria-hidden="true">↗</span></small></button>`).join('');
  $('pack-pagination').innerHTML=(state.offset?'<button class="pack-button" data-page="-1">Previous</button>':'')+(state.offset+40<q.total?'<button class="pack-button" data-page="1">Next 40</button>':'');
  if(state.busy)busy(true);
 }
 async function open(shipmentId,orderIds,buyerOrder=null){if(!canLeave())return;busy(true);try{state.detail=await rpc(buyerOrder?'buyer':'detail',buyerOrder?{buyer_order_id:buyerOrder}:{shipment_id:shipmentId||null,order_ids:orderIds||[]});state.buyerOrder=buyerOrder;message('');state.dirty=false;state.uploads=[];renderDetail();document.querySelector('.packaging-page').classList.add('has-detail');$('pack-detail').scrollIntoView({block:'start'});const url=new URL(location.href);url.search='';url.searchParams.set(shipmentId?'package':buyerOrder?'buyer_order':'order',shipmentId||buyerOrder||orderIds[0]);history.replaceState(null,'',url);renderQueue();}finally{busy(false);}}
 async function mutate(action,extra={}){
  const s=state.detail?.shipment;const args={shipment_id:s?.id,revision:s?.revision,...extra};
  const key=action+JSON.stringify(args);const request=state.requests.get(key)||crypto.randomUUID();state.requests.set(key,request);
  const drafts=state.dirty&&!['start','contents','pack','reopen','cancel'].includes(action)?[...document.querySelectorAll('[data-line]')].map(i=>[i.dataset.line,i.value]):[];
  const result=await rpc(action,{...args,request_id:request});state.requests.delete(key);state.detail=result;if(result.shipment)state.buyerOrder=null;state.dirty=!!drafts.length;renderDetail();
  if(result.shipment?.id){const url=new URL(location.href);url.search='';url.searchParams.set('package',result.shipment.id);history.replaceState(null,'',url);}
  drafts.forEach(([id,value])=>{const input=[...document.querySelectorAll('[data-line]')].find(i=>i.dataset.line===id);if(input)input.value=value;});
  await queue().catch(()=>message('Saved successfully. Refresh the queue when the connection returns.',true));return result;
 }

 function mediaCard(p,index,source=false){return `<div class="pack-media" data-media-index="${index}" data-media-source="${source}"><div class="pack-media-placeholder">${p.media_type==='video'?'Video':'Photo'} · Load to view</div><a href="#" data-open-media="${index}" data-source="${source}">${esc(p.label||(source?'Order evidence':'Packaging '+(p.media_type==='video'?'video':'photo')))}</a>${!source&&editable()?`<button type="button" class="pack-button" data-remove-photo="${esc(p.id)}">Remove</button>`:''}</div>`;}
 function renderDetail(){const d=state.detail;if(!d)return;const proofWasOpen=$('pack-order-proof')?.open;media.reset(d);const s=d.shipment,can=editable(),working=s&&['in_progress','on_hold'].includes(s.status),claim=hasClaim();
  const buyers=[...new Map(d.orders.map(o=>{const name=o.buyer_username?.trim()||o.buyer_name||o.order_number;return [name.toLowerCase(),name];})).values()];
  const total=d.lines.reduce((n,l)=>n+(l.line_status==='fulfilled'?l.fulfilled_quantity:0),0),inBox=d.lines.reduce((n,l)=>n+l.packed_quantity,0);
  const blocked=d.issues.filter(i=>i.open&&i.blocking);
  $('pack-detail').innerHTML=`<header class="pack-detail-head"><div class="pack-detail-top"><button class="pack-button pack-back" data-back>‹ Queue</button><span class="pack-badge ${esc(s?.status||'')}">${esc(s?.prior_dispatch?'Already sent':labels[s?.status]||(d.orders.every(o=>o.ready)?'Ready to package':'Order reference'))}</span>${s?`<span class="pack-subtle">${inBox} ${s.prior_dispatch?'items recorded':'in this box'}</span>`:''}</div><h2>${s?esc(s.prior_dispatch?'Already sent · prior to rollout':s.tracking_code):esc(buyers.join(' · '))}</h2><p class="pack-muted">${s?esc(buyers.join(' · ')):d.orders.length+' order'+(d.orders.length===1?'':'s')+' · '+total+' item'+(total===1?'':'s')+' to review together'}</p>
   ${working?`<p class="pack-subtle">${claim?'You are packing this':s.claimed_until&&new Date(s.claimed_until)>new Date()?esc(s.claimed_name||'Another employee')+' is packing this':'Available to claim'}</p>`:''}
   ${s?.status==='on_hold'?`<div class="pack-notice error"><strong>On hold</strong><br>${esc(s.hold_reason)}${blocked.length?`<br>${blocked.length} blocking task${blocked.length===1?'':'s'} awaiting resolution.`:''}</div>`:''}
   ${s?.status==='ready'&&s.dispatch_date<today()?'<div class="pack-notice">Carried over from '+esc(s.dispatch_date)+'. Confirm it is still ready to leave today.</div>':''}
   ${working&&!claim?'<button class="pack-button primary" data-action="claim">Claim package</button>':''}
  ${s?.prior_dispatch?'<div class="pack-notice">The owner confirmed these orders were already sent before the packaging workflow was adopted. This is an administrative closeout, not a new inspection. Original order photos remain below; the exact carrier handoff date was not recorded.</div>':''}${media.summary()}</header>
  <section class="pack-section"><div class="pack-section-head"><h3>Orders in this package</h3><span>${d.orders.length} order${d.orders.length===1?'':'s'}</span></div>${d.orders.length>1?'<details class="pack-order-list"><summary>View order numbers & shipping labels</summary>':''}${d.orders.map(o=>`<div class="pack-order"><strong>${esc(o.order_number)}</strong><small>${esc(o.buyer_username||o.buyer_name)} · Ordered ${date(o.sale_date)}</small>${!o.ready?'<div class="pack-notice error">This order is not ready for Packaging.</div>':''}${o.tracking_number?`<small>Saved tracking: ${esc(o.tracking_number)}</small>`:''}<div class="pack-line-links"><a href="ebay-order-history.html?orderId=${encodeURIComponent(o.id)}" target="_blank" rel="noopener">Order history ↗</a>${o.label_file_path?`<a href="#" data-label-order="${esc(o.id)}">Shipping label ↗</a>`:''}</div></div>`).join('')}${d.orders.length>1?'</details>':''}
   ${!s&&d.orders.every(o=>o.ready)?`<p class="pack-instructions">Scan the shipping label to connect the right package. Its order numbers and buyer will be shown before you begin.</p><button class="pack-button primary" data-action="scan-order">${d.orders.length>1?'Scan buyer’s shipping label':'Scan this order’s label'}</button>`:''}
  </section>
  <section class="pack-section" id="pack-items"><div class="pack-section-head"><h3>${s?.prior_dispatch?'Items recorded as sent':'01 · Check the contents'}</h3><span>${total} fulfilled item${total===1?'':'s'}</span></div><p class="pack-instructions">${s?.prior_dispatch?'Previously fulfilled quantities, retained for the closeout audit.':'Confirm the quantity physically in this box. Items already in another package cannot be counted again.'}</p><div>${d.lines.map(l=>{const available=l.line_status==='fulfilled'?Math.max(0,l.fulfilled_quantity-l.other_quantity):0;return`<article class="pack-line"><div class="pack-line-info"><div><h3>${esc(l.item_title)}</h3><small>${esc(d.orders.find(o=>o.id===l.order_id)?.order_number)} · ${esc(l.custom_label||l.item_number||'')}</small><small>${l.quantity} ordered · ${l.fulfilled_quantity} fulfilled${l.other_quantity?` · ${l.other_quantity} in other packages`:''}${l.line_status!=='fulfilled'?' · '+esc(l.line_status):''}</small>${l.notes?`<p class="pack-instructions">${esc(l.notes)}</p>`:''}</div><label>${s?.prior_dispatch?'RECORDED SENT':'IN THIS BOX'}<input type="number" inputmode="numeric" min="0" max="${available}" step="1" value="${l.packed_quantity}" data-line="${esc(l.id)}" ${!can||s?.status==='on_hold'||!available?'disabled':''} aria-label="Quantity for ${esc(l.item_title)}"></label></div><a class="pack-button order-chat-link" href="email-triage.html?orderLineId=${encodeURIComponent(l.id)}&from=packaging" target="_blank" rel="noopener" aria-label="eBay chat for ${esc(l.item_title)}">eBay chat ↗</a><button type="button" class="certificate-trigger" data-certificate-line="${esc(l.id)}" data-certificate-title="${esc((d.orders.find(o=>o.id===l.order_id)?.order_number||'')+' · '+(l.item_title||'Order item'))}">CGL certificate</button>${media.lineHtml(l)}</article>`;}).join('')}</div>${can&&s.status!=='on_hold'?'<button class="pack-button" data-action="contents">Save checked quantities</button>':''}
   ${d.related_packages.length?`<details><summary>Other packages for these orders (${d.related_packages.length})</summary>${d.related_packages.map(p=>`<button class="pack-row" data-package="${esc(p.id)}"><strong>${esc(p.tracking_code||'Previously sent')}</strong><small>${esc(labels[p.status])}</small></button>`).join('')}</details>`:''}
  </section>
  ${media.completionHtml()}${media.otherHtml()}
  <section class="pack-section"><details id="pack-order-proof"><summary>Order notes & tasks <span class="pack-subtle">· ${d.tasks.length} tasks</span></summary>${d.order_events.filter(e=>e.notes).slice(0,40).map(e=>`<div class="pack-note"><p>${esc(e.notes)}</p><small>${esc(d.orders.find(o=>o.id===e.order_id)?.order_number)} · ${esc(e.signed_by_email)} · ${date(e.created_at)}</small></div>`).join('')}${d.tasks.map(t=>`<a class="pack-task" href="team-tasks.html?taskId=${encodeURIComponent(t.id)}&source=order" target="_blank" rel="noopener"><strong>${esc(t.title)}</strong><small>${esc(t.latest_note||t.question||'')}</small><small>${esc(t.status.replaceAll('_',' '))} · ${esc(t.assigned_to_email||'Unassigned')} · ${date(t.created_at)} ↗</small></a>`).join('')}${!d.order_events.length&&!d.tasks.length?'<p class="pack-instructions">No notes or tasks attached to these orders.</p>':''}</details></section>
  ${s?`<section class="pack-section"><div class="pack-section-head"><h3>02 · Packaging proof</h3><span>${d.evidence.length} files</span></div><p class="pack-instructions">${s.prior_dispatch?'Packaging evidence was not collected in this workflow before rollout.':'Take a clear photo of all items going into this box. Videos are optional.'}</p>${can?`<div class="pack-actions"><label class="pack-button pack-upload-label">▣ Take photo<input id="pack-camera" class="pack-file" type="file" accept="image/*" capture="environment"></label><label class="pack-button pack-upload-label">＋ Photos / videos<input id="pack-files" class="pack-file" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,video/mp4,video/quicktime,video/webm" multiple></label></div>`:''}<div id="pack-upload-status" aria-live="polite"></div><div class="pack-media-grid">${d.evidence.map((p,i)=>mediaCard(p,i)).join('')}</div>${!d.evidence.length&&!s.prior_dispatch?'<p class="pack-subtle">No packaging proof saved yet.</p>':''}</section>
  <section class="pack-section"><div class="pack-section-head"><h3>Notes & follow-up</h3></div>${can?'<div class="pack-actions"><button class="pack-button" data-action="note">Add note</button><button class="pack-button" data-action="issue">Report an issue</button></div>':''}${d.issues.map(i=>`<a class="pack-task" href="team-tasks.html?taskId=${encodeURIComponent(i.task_id)}&source=order" target="_blank" rel="noopener">${i.open&&i.blocking?'● Blocking · ':''}${esc(i.title)}<small>${esc(i.status.replaceAll('_',' '))} · ${esc(i.assigned_to_email||'')} ↗</small></a>`).join('')}${d.events.filter(e=>e.notes).map(e=>`<div class="pack-note"><p>${esc(e.notes)}</p><small>${esc(e.actor||'Staff')} · ${date(e.created_at)}</small></div>`).join('')}</section>
  <section class="pack-section"><details><summary>Package activity</summary>${d.events.map(e=>`<div class="pack-note"><p>${esc({start:'Package started',pack:'Packed · Sending today',dispatch:'Dispatched',prior_dispatch_closeout:'Previously sent · owner-confirmed closeout',contents:'Contents checked',evidence:'Evidence attached',issue:'Issue reported',sending_today:'Dispatch date reconfirmed',reopen:'Package reopened',cancel:'Package cancelled',claim:'Package claimed',resume:'Packing resumed',remove_evidence:'Evidence removed'}[e.action]||e.action)}</p><small>${esc(e.actor||'Staff')} · ${date(e.created_at)}</small></div>`).join('')}</details></section>
  <footer class="pack-footer">${can&&s.status==='in_progress'?'<button class="pack-button primary" data-action="pack">Packaged · Sending today →</button><p>Recorded as ready for today’s dispatch. Confirm carrier handoff separately.</p>':can&&s.status==='on_hold'?`<button class="pack-button primary" data-action="resume" ${blocked.length?'disabled':''}>Issue resolved · Resume packing</button>`:s.status==='ready'?`<button class="pack-button primary" data-action="${s.dispatch_date<today()?'sending_today':'dispatch'}">${s.dispatch_date<today()?'Reconfirm sending today':'Confirm dispatched →'}</button><p>${s.dispatch_date<today()?'Review the package before updating the planned date.':'Use after the package has actually left with the carrier.'}</p>`:s.status==='dispatched'?`<p>${s.prior_dispatch?'Closeout recorded '+date(s.created_at):'Dispatched '+date(s.dispatched_at)}</p>`:''}<button class="pack-button" data-action="next">Scan next package</button>${state.admin&&!s.prior_dispatch?'<details><summary>Corrections</summary><p class="pack-instructions">Corrections are audited and never adjust inventory.</p><div class="pack-actions"><button class="pack-button" data-action="reopen">Reopen with reason</button><button class="pack-button danger" data-action="cancel">Cancel package</button></div></details>':''}</footer>`:''}`;
  if(proofWasOpen)$('pack-order-proof').open=true;media.mount();loadMedia(false);renderUploads();if(state.busy)busy(true);
 }
 async function signed(p,force=false){const key=p.bucket+'/'+p.path;const cached=state.urls.get(key);if(!force&&cached&&cached.until>Date.now())return cached.url;const {data,error}=await state.client.storage.from(p.bucket).createSignedUrl(p.path,600);if(error||!data?.signedUrl)throw Error('Could not open this file. Try again.');state.urls.set(key,{url:data.signedUrl,until:Date.now()+480000});return data.signedUrl;}
 async function loadMedia(source){const list=state.detail?.evidence||[];await Promise.allSettled([...document.querySelectorAll(`[data-media-source="${source}"]`)].map(async el=>{const p=list[Number(el.dataset.mediaIndex)];if(!p)return;try{const url=await signed(p);if(!el.isConnected)return;const link=el.querySelector('a');link.href=url;link.target='_blank';link.rel='noopener';const placeholder=el.querySelector('.pack-media-placeholder');if(placeholder){const media=document.createElement(p.media_type==='video'?'video':'img');media.src=url;if(p.media_type==='video'){media.controls=true;media.preload='none';media.playsInline=true;}else{media.alt=p.label||'Order photo';media.loading='lazy';}placeholder.replaceWith(media);}}catch{const box=el.querySelector('.pack-media-placeholder');if(box)box.textContent='Tap below to retry';}}));}
 let dialogAction=null;
 function dialog(title,body,submit,action){$('pack-dialog-title').textContent=title;$('pack-dialog-body').innerHTML=body;$('pack-dialog-submit').textContent=submit;$('pack-dialog-submit').hidden=false;$('pack-dialog-error').textContent='';dialogAction=action;$('pack-dialog').showModal();}
 async function scan(){if(!canLeave())return;const input=$('pack-barcode').value.trim();if(!input){$('pack-barcode').focus();return;}busy(true);try{const result=await rpc('scan',{tracking:input});
   if(result.shipment_id){busy(false);await open(result.shipment_id);message('Existing package opened. Scanning again does not create a duplicate.');return;}
   const candidates=result.matches.map(c=>{const all=c.buyer_order_ids||[];const combine=all.length>c.order_ids.length&&c.order_ids.every(id=>all.includes(id));return {...c,combine,order_ids:combine?all:c.order_ids,orders:combine?c.buyer_orders:c.orders};});
   if(candidates.length){dialog(candidates.length>1?'Choose the matching shipment':'Check the label & orders',`<p class="pack-instructions">Tracking ${esc(result.tracking)}. Match these order numbers to the shipping label before starting.</p>${candidates.map((c,i)=>`<label class="pack-choice pack-check"><input type="radio" name="match" value="${i}" ${candidates.length===1?'checked':''} required><span><strong>${esc([...new Set(c.orders.map(o=>o.buyer))].join(' · '))}</strong><small>${c.orders.length} order${c.orders.length===1?'':'s'} in this package</small>${c.orders.map(o=>`<span>${esc(o.order_number)}${!o.ready?' · NOT READY':''}</span>`).join('')}${c.combine?'<small>Includes the other ready orders for this buyer.</small>':''}</span></label>`).join('')}${candidates.some(c=>c.combine)?'<label class="pack-check"><input type="checkbox" name="confirm_buyer" required>All these orders belong to the recipient on this label and will go in this one package.</label><p class="pack-instructions">Check any other saved shipping labels before combining. Use only the scanned label on this package.</p>':''}`,'Start packing',async form=>{const match=candidates[Number(form.get('match'))];if(!match.orders.every(o=>o.ready))throw Error('All orders on this label must be completed in Pending Orders first.');await mutate('start',{tracking:result.tracking,order_ids:match.order_ids,...(match.combine?{combine_buyer:true,confirm_buyer:form.get('confirm_buyer')==='on',note:'Buyer orders combined after checking the recipient and shipping label.'}:{})});document.querySelector('.packaging-page').classList.add('has-detail');});
   }else{const eligible=state.detail?.orders?.filter(o=>o.ready)||[];
    if(eligible.length){dialog('Link this external label',`<div class="pack-notice">No saved label matches this tracking number. Verify the shipping label belongs to every order below.</div><p>${esc(result.tracking)}</p>${eligible.map(o=>`<p class="pack-instructions"><strong>${esc(o.order_number)}</strong> · ${esc(o.buyer_username||o.buyer_name)}</p>`).join('')}<label class="pack-check"><input type="checkbox" name="confirm" required>I checked the recipient and order numbers on the shipping label.</label><label>Reason / source of label<textarea name="note" required placeholder="For example: label purchased outside eBay"></textarea></label>`,'Link & start packing',async form=>{await mutate('start',{tracking:result.tracking,order_ids:eligible.map(o=>o.id),confirm_link:true,...(eligible.length>1?{combine_buyer:true,confirm_buyer:form.get('confirm')==='on'}:{}),note:form.get('note')});document.querySelector('.packaging-page').classList.add('has-detail');});
    }else message('No saved label matches. Find the completed order in To package, open it, then scan again to link an external label.',true);
   }
  }finally{busy(false);}}
 function noteField(label='Note'){return `<label>${label}<textarea name="note" required maxlength="10000"></textarea></label>`;}
 async function action(name){if(state.busy)return;
  if(name==='next'||name==='scan-order'){if(!canLeave())return;state.dirty=false;state.uploads=[];if(name==='next'){state.detail=null;state.buyerOrder=null;$('pack-detail').innerHTML='<div class="pack-welcome"><h2>Ready for the next package</h2><p>Scan its shipping label above.</p></div>';}document.querySelector('.packaging-page').classList.remove('has-detail');$('pack-barcode').value='';$('pack-barcode').focus();$('pack-barcode').scrollIntoView({block:'center'});return;}
  if(name==='contents'){const items=[...document.querySelectorAll('[data-line]')].filter(i=>!i.disabled).map(i=>({line_id:i.dataset.line,quantity:Number(i.value)}));if(items.some(i=>!Number.isInteger(i.quantity)||i.quantity<0))throw Error('Enter whole, nonnegative quantities.');busy(true);try{await mutate('contents',{items});message('Package quantities saved.');}finally{busy(false);}return;}
  if(name==='claim'){busy(true);try{await mutate('claim');message('Package claimed. You can now check and pack it.');}finally{busy(false);}return;}
  if(name==='pack'){if(state.dirty)throw Error('Save checked quantities before finishing.');if(state.uploads.length)throw Error('Finish or remove pending uploads before packing.');const d=state.detail;const count=d.lines.reduce((n,l)=>n+l.packed_quantity,0);dialog('Ready to send today?',`<p class="pack-instructions">${count} confirmed item${count===1?'':'s'} · ${d.evidence.filter(e=>e.media_type==='image').length} packaging photos</p><p class="pack-instructions">Tracking ${esc(d.shipment.tracking_code)}</p><label class="pack-check"><input type="checkbox" required>I checked the contents and the shipping label. This package is ready to leave today.</label>`,'Packaged · Sending today',async()=>{await mutate('pack');message('Package saved to Sending today. Scan the next label when ready.');});return;}
  if(name==='dispatch'||name==='sending_today'){dialog(name==='dispatch'?'Confirm carrier handoff':'Send this package today',`<p class="pack-instructions">Tracking ${esc(state.detail.shipment.tracking_code)}</p><label class="pack-check"><input type="checkbox" required>${name==='dispatch'?'The package has physically left with the carrier.':'I reviewed this package and it is ready to leave today.'}</label>`,'Confirm',async()=>{await mutate(name);message(name==='dispatch'?'Dispatch recorded.':'Sending today confirmed.');});return;}
  if(name==='issue'){if(!state.staff)state.staff=await rpc('staff');dialog('Report an issue',`<p class="pack-instructions">Assign the next step to the person who can resolve it. They will receive a task notification.</p><label>Order<select name="order_id">${state.detail.orders.map(o=>`<option value="${esc(o.id)}">${esc(o.order_number)} · ${esc(o.buyer_username||o.buyer_name)}</option>`).join('')}</select></label><label>What is needed?<select name="kind"><option value="work">Work · something needs to be done</option><option value="decision">Decision · approval or instructions</option></select></label><label>Person responsible<select name="owner" required><option value="">Choose a person</option>${state.staff.map(e=>`<option value="${esc(e.user_id)}">${esc(e.name)}</option>`).join('')}</select></label>${noteField('What is missing, defective or needed?')}<label>Due date and time<input type="datetime-local" name="due" required></label><label class="pack-check"><input type="checkbox" name="blocking" checked>Hold this package until the task is resolved and accepted.</label><p class="pack-instructions">Saved packaging photos and videos will be attached to the task.</p>`,'Create task',async form=>{await mutate('issue',{order_id:form.get('order_id'),kind:form.get('kind'),owner:form.get('owner'),note:form.get('note'),due_at:new Date(form.get('due')).toISOString(),blocking:form.get('blocking')==='on'});message('Task assigned. The responsible person will receive an update.');});return;}
  const names={note:['Add a packaging note','Save note'],resume:['Resolve the hold','Resume packing'],reopen:['Reopen this package','Reopen package'],cancel:['Cancel this package','Cancel package']};
  if(names[name]){const [title,submit]=names[name];dialog(title,(name==='cancel'?'<p class="pack-instructions">This releases its item quantities for another package. Its evidence and activity remain in History.</p>':'')+noteField(name==='note'?'Note':'Reason'),submit,async form=>{await mutate(name,{note:form.get('note')});message('Package updated.');});}
 }
 function renderUploads(){const el=$('pack-upload-status');if(!el)return;el.innerHTML=state.uploads.map((u,i)=>`<div class="pack-notice ${u.error?'error':''}">${esc(u.file.name)} · ${esc(u.error||u.status)}${u.error?`<div class="pack-actions"><button class="pack-button" data-upload-retry="${i}">Retry</button><button class="pack-button" data-upload-remove="${i}">Remove from upload queue</button></div>`:''}</div>`).join('');if(state.busy)busy(true);}
 async function uploadOne(u){u.error=null;u.status='Uploading…';renderUploads();try{if(!u.uploaded){const {error}=await state.client.storage.from('team-task-evidence').upload(u.path,u.file,{upsert:false,contentType:u.file.type});if(error&&error.statusCode!=='409'&&error.statusCode!==409)throw error;u.uploaded=true;}u.status='Saving evidence…';renderUploads();await mutate('evidence',{path:u.path,label:u.file.name});state.uploads=state.uploads.filter(x=>x!==u);renderUploads();}catch(e){u.error=e.message||'Upload failed. Your file is still here for retry.';renderUploads();}}
 async function files(list){if(!editable()||state.busy)return;const allowed=['image/jpeg','image/png','image/webp','image/heic','image/heif','video/mp4','video/quicktime','video/webm'];const incoming=[...list];if(state.uploads.length+state.detail.evidence.length+incoming.length>30)throw Error('Use up to 30 evidence files per package.');if(incoming.some(f=>!allowed.includes(f.type)||f.size>50*1024*1024||!f.size))throw Error('Use photos or MP4, MOV or WebM videos up to 50 MB each.');for(const file of incoming)state.uploads.push({file,path:`packaging/${state.detail.shipment.id}/${state.user}/${crypto.randomUUID()}.${file.name.split('.').pop().replace(/[^a-z0-9]/gi,'').slice(0,8)||'bin'}`,status:'Waiting'});busy(true);try{for(const u of [...state.uploads].filter(u=>!u.error))await uploadOne(u);}finally{busy(false);}}
 function safe(fn){return async e=>{try{await fn(e);}catch(err){message(err.message,true);}};}
 async function init(){state.client=window.supabase;if(!state.client?.rpc)return;await queue();const params=new URLSearchParams(location.search);if(params.get('package'))await open(params.get('package'));else if(params.get('buyer_order'))await open(null,null,params.get('buyer_order'));else if(params.get('order'))await open(null,[params.get('order')]);}
 $('pack-scan-form').addEventListener('submit',safe(async e=>{e.preventDefault();await scan();}));
 $('pack-refresh').addEventListener('click',safe(async()=>{if(!canLeave())return;await queue();if(state.detail)await open(state.detail.shipment?.id,state.detail.orders.map(o=>o.id),state.buyerOrder);message('Packaging refreshed.');}));
 let searchTimer;$('pack-search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(safe(async()=>{state.search=$('pack-search').value.trim();state.offset=0;await queue();}),250);});
 document.querySelector('.packaging-page').addEventListener('input',e=>{if(e.target.matches('[data-line]'))state.dirty=true;});
 document.querySelector('.packaging-page').addEventListener('change',safe(async e=>{if(e.target.matches('#pack-files,#pack-camera'))await files(e.target.files);}));
 document.querySelector('.packaging-page').addEventListener('click',safe(async e=>{const el=e.target.closest('button,a');if(!el)return;
  if(el.dataset.view){if(!canLeave())return;state.view=el.dataset.view;state.offset=0;document.querySelector('.packaging-page').classList.remove('has-detail');await queue();}
  else if(el.dataset.page){state.offset+=Number(el.dataset.page)*40;await queue();}
  else if(el.hasAttribute('data-package')||el.dataset.order){await open(el.dataset.package,el.dataset.order?[el.dataset.order]:null,el.dataset.buyerOrder||null);}
  else if(el.hasAttribute('data-back')){if(canLeave())document.querySelector('.packaging-page').classList.remove('has-detail');}
  else if(el.dataset.action)await action(el.dataset.action);
  else if(el.dataset.removePhoto){busy(true);try{await mutate('remove_evidence',{evidence_id:el.dataset.removePhoto});}finally{busy(false);}}
  else if(el.hasAttribute('data-upload-retry')){busy(true);try{await uploadOne(state.uploads[Number(el.dataset.uploadRetry)]);}finally{busy(false);}}
  else if(el.hasAttribute('data-upload-remove')){state.uploads.splice(Number(el.dataset.uploadRemove),1);renderUploads();}
  else if(el.dataset.labelOrder){e.preventDefault();const o=state.detail.orders.find(o=>o.id===el.dataset.labelOrder);const win=window.open('about:blank','_blank');try{const url=await signed({bucket:o.label_storage_bucket||'ebay-labels',path:o.label_file_path});if(win){win.opener=null;win.location.href=url;}}catch(err){win?.close();throw err;}}
  else if(el.hasAttribute('data-open-media')&&el.getAttribute('href')==='#'){e.preventDefault();await loadMedia(el.dataset.source==='true');}
 }));
 document.querySelectorAll('[data-dialog-close]').forEach(b=>b.addEventListener('click',()=>{if(!state.busy)$('pack-dialog').close();}));
 $('pack-dialog').addEventListener('cancel',e=>{if(state.busy)e.preventDefault();});
 $('pack-dialog-form').addEventListener('submit',async e=>{e.preventDefault();if(state.busy)return;const data=new FormData(e.target);busy(true);$('pack-dialog-error').textContent='';try{await dialogAction(data);$('pack-dialog').close();}catch(err){$('pack-dialog-error').textContent=err.message;}finally{busy(false);}});
 window.addEventListener('beforeunload',e=>{if(state.dirty||state.uploads.length||state.busy){e.preventDefault();e.returnValue='';}});
 setInterval(()=>{if(document.visibilityState==='visible'&&!state.busy)queue().catch(()=>{});},60000);
 if(window.supabase?.rpc)init().catch(e=>message(e.message,true));else document.addEventListener('supabase-ready',()=>init().catch(e=>message(e.message,true)),{once:true});
})();
