import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {createServer} from 'node:http';
import {test,before,after} from 'node:test';
import {chromium,webkit} from '@playwright/test';
import vm from 'node:vm';
const root=new URL('../',import.meta.url);let server,browser,origin;
before(async()=>{
 server=createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(1);if(!/^[\w./-]+$/.test(name)||name.includes('..'))return res.writeHead(404).end();try{let content=await readFile(new URL(name,root));if(name.endsWith('.html'))content=content.toString().replace(/<script\b[\s\S]*?<\/script>/gi,tag=>/src="(?:ebay-live|live-sales)\.js/.test(tag)?tag:'');res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(content);}catch{res.writeHead(404).end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;
 browser=await(process.env.INVSTO_ITEM_BROWSER==='webkit'?webkit:chromium).launch();
});
after(async()=>{await browser.close();await new Promise(r=>{server.close(r);server.closeAllConnections();});});
const tile=(id='123456789012',status='Paid',title='#001 - Watch',buyer='testbuyer')=>`<div data-testid="listing-tile"><input data-testid="checkbox-${id}" type="checkbox"><span class="_statusPill_hash_1">${status}</span><input data-testid="ordinal-id" value="29"><button data-testid="inline-edit-title"><span>${title}</span></button><span class="_price_hash_1">$100.00</span><span class="_soldLabel_hash_1" title="${buyer}">${buyer}</span><span class="_statusText_hash_1">${status}</span></div>`;
const row=(action='won the auction',buyer='testbuyer',title='#001 - Watch')=>`<div class="_rowContent_hash_1"><div class="_messageLine_hash_1"><span class="_username_hash_1">${buyer}</span><span class="_actionSuccess_hash_1">${action}</span><span class="_timestamp_hash_1">10:03 AM</span></div><div class="_itemSummary_hash_1"><span>$100.00</span><span class="_listingTitle_hash_1">${title}</span></div></div>`;
async function parser(t,html){const page=await browser.newPage();t.after(()=>page.close());await page.setContent(html);await page.addScriptTag({path:new URL('../tools/ebay-live-capture/parser.js',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')});return page;}
test('parser distinguishes explicit paid badge from auction wins and AUC labels',async t=>{const page=await parser(t,tile()+'<div id="activity-panel">'+row()+'</div>');const r=await page.evaluate(()=>InvstoLiveParser.parse(document));assert.deepEqual(r.events.map(e=>e.kind),['paid','won']);assert.equal(r.events[1].listing_id,'123456789012');await page.setContent(tile('123456789012','AUC'));assert.equal((await page.evaluate(()=>InvstoLiveParser.parse(document))).events.length,0);});
test('ambiguous listing titles and unfamiliar payment text remain unverified',async t=>{const page=await parser(t,tile()+tile('222222222222')+'<div id="activity-panel">'+row('payment maybe received')+'</div>');const r=await page.evaluate(()=>InvstoLiveParser.parse(document));const activity=r.events.find(e=>e.source==='activity');assert.equal(activity.kind,'unknown');assert.equal(activity.listing_id,undefined);});
test('failures without buyer details and identical repeated auction notifications require review',async t=>{const page=await parser(t,tile('123456789012','Payment failed','#001 - Watch','')+'<div id="activity-panel">'+row()+row()+'</div>');const r=await page.evaluate(()=>InvstoLiveParser.parse(document));assert.equal(r.events[0].kind,'failed');assert.equal(r.events[0].buyer,'');assert.ok(r.events.some(e=>e.kind==='unknown'&&e.key.startsWith('ambiguous|')));});
test('unrecognized currencies are never parsed as a USD paid price',async t=>{const page=await parser(t,tile().replace('$100.00','C$100.00'));assert.equal((await page.evaluate(()=>InvstoLiveParser.parse(document))).events.length,0);});
async function open(t,query=''){
 const context=await browser.newContext({viewport:{width:390,height:844}});t.after(()=>context.close());await context.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());
 await context.addInitScript(()=>{
  const user={id:'worker',email:'worker@example.invalid'},employee={id:'seller',user_id:'worker',display_name:'Test seller',active:true,role:'admin'};
  window.lucide={createIcons(){}};window.calls=[];window.mockItems=[];window.mockLots=[];window.failDashboard=false;window.failClose=false;
  window.showSession={id:'show',session_code:'SHOW',title:'Test show',status:'active',store_id:'store',primary_seller_employee_id:'seller',started_at:new Date().toISOString()};
  window.dashboard={connection:{event_id:'EVENT123',session_id:'show',capture_ready:true,source_seen_at:new Date().toISOString(),active_seller_id:'seller',fee_percent:null,fee_fixed:null,shipping_per_sale:null},attempts:[{id:'sale',event_id:'EVENT123',listing_id:'123456789012',listing_title:'#001 - Test watch',buyer:'testbuyer',amount:100,payment_state:'paid',seller_id:'seller',seller_name:'Test seller',created_at:new Date().toISOString(),units:0}],unmatched:[]};
  window.printStations={printLabel:async(xml)=>{window.calls.push({name:'print',xml});return {mode:'remote-queue',stationName:'Test printer'};}};
  window.supabase={auth:{getSession:async()=>({data:{session:{user}}})},storage:{from:()=>({createSignedUrl:async()=>({data:{signedUrl:''}})})},from(table){
   let filters=[],limit=1000;const all=()=>table==='employees'?[employee]:table==='store_locations'?[{id:'store',name:'Showroom',active:true}]:table==='live_sale_sessions'?[window.showSession]:table==='ebay_live_attempts'?window.dashboard.attempts:table==='live_sale_lots'?window.mockLots:table==='live_sale_lot_items'?window.mockItems:[];
   const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},in(){return q},is(){return q},order(){return q},limit(n){limit=n;return q},maybeSingle:async()=>({data:all().find(r=>filters.every(f=>f(r)))||null}),single:async()=>({data:all().find(r=>filters.every(f=>f(r)))||null}),then(fn){return Promise.resolve({data:all().filter(r=>filters.every(f=>f(r))).slice(0,limit)}).then(fn)}};return q;
  },rpc:async(name,args)=>{window.calls.push({name,args});if(name==='get_live_sale_seller_directory')return {data:[employee]};if(name==='get_ebay_live_dashboard')return window.failDashboard?{error:{message:'Network interrupted'}}:{data:structuredClone(window.dashboard)};
   if(name==='claim_ebay_live_bag'){const a=window.dashboard.attempts.find(a=>a.id===args._attempt_id);a.claimed_by='worker';a.lot_id='lot';const lot={id:'lot',session_id:'show',auction_number:'EB-29-SALE',lot_code:'LIVE-TEST',status:'open',owner_employee_id:'seller'};window.mockLots=[lot];return {data:lot};}
   if(name==='close_ebay_live_bag'){if(window.failClose)return {error:{message:'Payment is not confirmed for this bag'}};window.dashboard.attempts[0].closed_at=new Date().toISOString();return {data:null};}
   if(name==='resolve_ebay_live_attempt'){const a=window.dashboard.attempts.find(a=>a.id===args._attempt_id);if(args._action==='cancel_release'){a.resolved_at=new Date().toISOString();a.payment_state='cancelled';}return {data:null};}
   if(name==='create_live_sale_lot'){const l={id:'ordinary',session_id:'show',auction_number:args._auction_number,status:'open'};window.mockLots=[l];return {data:l};}
   return {data:null};
  }};
 });
 const page=await context.newPage();page.errors=[];page.on('pageerror',e=>page.errors.push(e.message));await page.goto(origin+'/live-sales.html'+query);await page.locator('#ebay-live-connected:visible').waitFor();await page.locator('[data-action="scan"]').waitFor();return page;
}
test('linked show waits for paid selection and claims a bag through existing scan UI',async t=>{const p=await open(t);assert.equal(await p.locator('#item-scan').isDisabled(),true);assert.equal(await p.evaluate(()=>calls.some(c=>c.name==='create_live_sale_lot')),false);await p.locator('[data-action=scan]').click();await p.waitForFunction(()=>!document.getElementById('item-scan').disabled);assert.equal(await p.locator('#auction-number').getAttribute('readonly'),'');assert.match(await p.locator('#ebay-live-current').innerText(),/testbuyer.*\$100/);assert.deepEqual(p.errors,[]);});
test('late failure disables active phone scanner and removes the sale from completed totals',async t=>{const p=await open(t);await p.locator('[data-action=scan]').click();await p.waitForFunction(()=>!document.getElementById('item-scan').disabled);await p.evaluate(()=>{dashboard.attempts[0].payment_state='failed';});await p.locator('#ebay-live-refresh').click();await p.waitForFunction(()=>document.getElementById('item-scan').disabled);await p.locator('#ebay-live-filter').selectOption('attention');assert.match(await p.locator('#ebay-live-queue').innerText(),/STOP.*check this bag/);assert.equal(await p.locator('[data-action=scan]').count(),0);assert.match(await p.locator('#ebay-live-totals').innerText(),/0 \/ \$0.00/);});
test('stale capture and network failure block new scans',async t=>{const p=await open(t);await p.evaluate(()=>{dashboard.connection.source_seen_at=new Date(Date.now()-60000).toISOString();});await p.locator('#ebay-live-refresh').click();await p.waitForFunction(()=>document.querySelector('[data-action=scan]').disabled);assert.match(await p.locator('#ebay-live-health').innerText(),/disconnected/);await p.evaluate(()=>{dashboard.connection.source_seen_at=new Date().toISOString();failDashboard=true;});await p.locator('#ebay-live-refresh').click();await p.waitForFunction(()=>document.getElementById('ebay-live-message').textContent.includes('Network interrupted'));assert.equal(await p.locator('#item-scan').isDisabled(),true);});
test('bag closes without invoking a printer; rejected close keeps the selected bag',async t=>{const p=await open(t);await p.locator('[data-action=scan]').click();await p.waitForFunction(()=>!document.getElementById('item-scan').disabled);await p.evaluate(()=>{failClose=true;});await p.evaluate(()=>ebayLive.closeCurrent());assert.match(await p.locator('#ebay-live-message').innerText(),/not confirmed/);assert.equal(await p.evaluate(()=>ebayLive.current().id),'sale');await p.evaluate(()=>{failClose=false;});await p.evaluate(()=>ebayLive.closeCurrent());assert.equal(await p.evaluate(()=>calls.filter(c=>c.name==='print').length),0);assert.equal(await p.locator('[data-action=print]').count(),1);await p.locator('[data-action=print]').click();await p.waitForFunction(()=>calls.some(c=>c.name==='print'));assert.match(await p.evaluate(()=>calls.find(c=>c.name==='print').xml),/TESTBUYER/);assert.doesNotMatch(await p.evaluate(()=>calls.find(c=>c.name==='print').xml),/EB-29-SALE/);});
test('local cancellation requires physical bag confirmation and records the reason',async t=>{const p=await open(t);await p.locator('[data-action=review]').click();await p.locator('#ebay-review-action').selectOption('cancel_release');await p.locator('#ebay-review-note').fill('Checked eBay and removed the watch from the bag');await p.locator('#ebay-review-save').click();assert.match(await p.locator('#ebay-review-error').innerText(),/physical bag/);assert.equal(await p.evaluate(()=>calls.some(c=>c.name==='resolve_ebay_live_attempt')),false);await p.locator('#ebay-review-physical').check();await p.locator('#ebay-review-save').click();await p.locator('#ebay-live-review').waitFor({state:'hidden'});assert.equal(await p.evaluate(()=>calls.find(c=>c.name==='resolve_ebay_live_attempt').args._action),'cancel_release');});
test('phone layout fits, seller data is escaped, and missing prices stay explicit',async t=>{const p=await open(t);await p.setViewportSize({width:320,height:740});await p.evaluate(()=>{dashboard.attempts[0].listing_title='<img src=x onerror="window.injected=true">';dashboard.attempts[0].closed_at=new Date().toISOString();dashboard.attempts[0].minimum_total=null;dashboard.attempts[0].estimated_profit=null;});await p.locator('#ebay-live-refresh').click();await p.locator('#ebay-live-filter').selectOption('closed');assert.equal(await p.evaluate(()=>!!window.injected),false);assert.match(await p.locator('#ebay-live-totals').innerText(),/1 bags missing/);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),JSON.stringify(await p.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth).slice(0,18).map(e=>({tag:e.tagName,id:e.id,cls:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right})))));await mkdir(new URL('../test-results',import.meta.url),{recursive:true});await p.screenshot({path:new URL('../test-results/ebay-live-phone.png',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1'),fullPage:true});assert.deepEqual(p.errors,[]);});
test('receiver acknowledges only the linked event after ingest succeeds',async t=>{const p=await open(t,'?capture=1');await p.evaluate(()=>{window.acks=[];window.addEventListener('message',e=>{if(e.data?.type==='INVSTO_LIVE_ACK')acks.push(e.data)});window.postMessage({type:'INVSTO_LIVE_BATCH',id:'wrong',payload:{event_id:'OTHER',events:[],health:{}}},location.origin);});await p.waitForFunction(()=>acks.length===1);assert.equal(await p.evaluate(()=>acks[0].ok),false);await p.evaluate(()=>window.postMessage({type:'INVSTO_LIVE_BATCH',id:'right',payload:{event_id:'EVENT123',events:[],health:{}}},location.origin));await p.waitForFunction(()=>acks.length===2);assert.equal(await p.evaluate(()=>acks[1].ok),true);assert.equal(await p.evaluate(()=>calls.filter(c=>c.name==='ingest_ebay_live_events').length),1);});
test('extension outbox persists failures until receiver commit and retries after worker restart',async()=>{
 const source=await readFile(new URL('../tools/ebay-live-capture/worker.js',import.meta.url),'utf8');let stored={},handler,accept=false,received=[];
 const chrome={storage:{local:{get:async()=>structuredClone(stored),set:async v=>{stored=structuredClone(v)}}},runtime:{id:'extension',onMessage:{addListener:fn=>{handler=fn}}},alarms:{create(){},onAlarm:{addListener(){}}},tabs:{sendMessage:async(tab,msg)=>{received.push(msg);return {ok:accept,error:'Offline'}}}};
 const boot=()=>vm.runInNewContext(source,{chrome,URL,Date,Promise,Error,Object,Number,String});boot();
 const send=(message,url,id=1)=>new Promise(resolve=>handler(message,{id:'extension',tab:{id,url}},resolve));
 await send({type:'INVSTO_CAPTURE',event_id:'EVENT123',events:[{key:'failure',kind:'failed'}],health:{ready:true}},'https://www.ebay.com/ebaylive/host/events/EVENT123');assert.equal(Object.keys(stored.capture.events).length,1);
 await send({type:'INVSTO_RECEIVER'},'https://antdamus.github.io/Invsto/live-sales.html?capture=1',2);assert.equal(Object.keys(stored.capture.events).length,1);
 boot();accept=true;await send({type:'INVSTO_RECEIVER'},'https://antdamus.github.io/Invsto/live-sales.html?capture=1',2);assert.equal(Object.keys(stored.capture.events).length,0);assert.equal(received.at(-1).payload.events[0].kind,'failed');
});
test('capture sends explicit payment evidence and emits a stopped heartbeat',async t=>{
 const page=await browser.newPage();t.after(()=>page.close());await page.goto(origin+'/ebaylive/host/events/EVENT123');await page.setContent('<button role="tab" aria-selected="true">Activity</button><button role="tab" aria-selected="true">Sold (1)</button>'+tile()+'<div id="activity-panel"><div aria-label="Filter activity"><button aria-pressed="true">All</button></div>'+row()+'</div>');
 await page.evaluate(()=>{window.packets=[];window.chrome={runtime:{sendMessage:async m=>{packets.push(m);return {ok:true,status:'Connected'}}}};});
 for(const name of ['parser','capture'])await page.addScriptTag({path:new URL(`../tools/ebay-live-capture/${name}.js`,import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')});
 assert.equal(await page.evaluate(()=>packets.length),0);await page.getByRole('button',{name:'Start Invsto capture',exact:true}).click();await page.waitForFunction(()=>packets.some(p=>p.health.ready));const first=await page.evaluate(()=>packets[0]);assert.equal(first.event_id,'EVENT123');assert.deepEqual(first.events.map(e=>e.kind),['paid','won']);await page.getByRole('button',{name:'Stop Invsto capture',exact:true}).click();await page.waitForFunction(()=>packets.some(p=>!p.health.ready));
});
test('ordinary unlinked sessions retain the manual bag workflow',async t=>{const p=await open(t);await p.evaluate(async()=>{dashboard.connection=null;dashboard.attempts=[];await prepareNextBag();});assert.equal(await p.evaluate(()=>calls.some(c=>c.name==='create_live_sale_lot')),true);assert.equal(await p.locator('#auction-number').getAttribute('readonly'),null);assert.equal(await p.locator('#item-scan').isDisabled(),false);assert.deepEqual(p.errors,[]);});
